### ISSUE TITLE
Theodore pattern back pleat

### ISSUE THREAD

**Issue by reeves99** [freesewing/freesewing#10]
The back pleat seems to be too long.  It extends past the pocket line to the seat circumference narrowing the circumference at the pocket line.
![unnamed-2](https://user-images.githubusercontent.com/46247494/54040038-40788800-4179-11e9-90cb-d9a006eb0f52.jpg)

Also, as drafted, the pattern has too much ease at the crotch and not enough at the seat.  From what I can see the pattern doesn't use seat circumference in its calculations.  Is that right?

**Comment by joostdecock** [comment]
As is mentioned [on the pattern page](https://freesewing.org/patterns/theodore) Theo(dore) implements the Aldrich draft method. Which is, unfortunately, not great.

It uses few measurements, and is not very adapted to different scenarios. This means that for some people it works great, for others it doesn't.

This does not live up to our _made to measure_ sewing patterns goal, and sure enough, I consider this pattern to be below our standards.
Which is why it will not be ported to JS for freesewing v2. Instead, I will replace it with a trouser pattern of my own design.

I realize this is not helpful to you right now, but we won't fix this deprecated pattern.

**Comment by reeves99** [comment]
Hi Joost
Thanks for replying!!!
I must apologize for not carefully reading the Theodore documentation.  I
hope I haven’t offended you with my feedback....Because I’m deeply
appreciative of the time and effort you’ve put in to promote and encourage
the handmade garment movement.
I look forward to trying your new design.
I’ve been trying for two months to create a trouser pattern for myself. I
adjusted a Burda pattern. Then I drafted a pattern from on-line
instructions from India. Then Theodore.
And I’ve come across some decent tailoring books.
I’m not there yet, but what’s happening is that I’m actually beginning to
figure out some fitting logic. If I do A, I can expect result B. (Well,
sometimes.)
Respectfully,
Phil

**Comment by joostdecock** [comment]
>  I hope I haven’t offended you with my feedback

Of course not, you did the right thing by creating this issue. It's just that I prefer to be honest about the shortcomings of the pattern.

Trousers aren't simple. I've got a trouser block [on my to-do list for 2 years or so](https://github.com/joostdecock/TrentTrouserBlock). 

Making one that fits yourself is ultimately not that hard with some trial and error. But making one that fits a variety of bodies is non-trivial to say the least. But I'll get it done or die trying 😉
