### ISSUE TITLE
Sizing issue in simon

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#100]
@GlassSteel writes:

> *Anyone made the Simon shirt, that might know what I'm doing wrong? I've just about maxed out the ease options and it's still super slim cut - like, I can't bend my arm the sleeve is so slim. I'm 14.75" neck, 36.5" chest, 31" natural waist, 11" bicep, 6.5" wrist - in other words, not a big guy and I'm used to slim cuts but I can't make this one work!*

Obviously, this is kind of a big deal. There's 3 things that come to mind that could cause this:

 - There's a bug in Simon
 - There's a bug in Brian
 - The option defaults and range are poorly chosen

**Comment by GlassSteel** [comment]
If you can tell me a couple other patterns that inherit from Brian, I can try to determine if that's where the bug is.

**Comment by joostdecock** [comment]
Patterns that inherit from Brian:

 - aaron
 - bent
 - huey
 - simon
 - sven
 - wahid

So if Sven looks ok, then it's most likely something simon-specific.

**Comment by GlassSteel** [comment]
Spent some more time methodically comparing - paperless render is a big help. I made new-site Simons with my 36.5" chest measure and 0%, 8% (default), and 20% (max) chest ease settings. The resulting garment sizes at the chest are exactly what you would expect: 36.5*1, 36.5*1.08, and 36.5*1.20.

Note that at my chest size, the 8% default is a meager 2.92" ease at the chest - quite slim!

For the old site Simon, it looks like the default is 6.25" chest east no matter what chest measure is given - this is pretty much along the lines of a commercial slim- or tailored- fit shirt.

So I wonder if rather than a programming bug, this is just highlighting a difference in methodology between the default chest ease of old and new Simons - a fixed 6.25" for everybody vs. 8% yielding 2.92" for me, a still rather trim 3.2" for a model with a 40" chest, and a whopping 78" chest needed to get the 6.25" of the old Simon.

I'm still not sure why my new Simon sleeves are so skinny, but given that my measurements are all on the small side, perhaps other percentage-based ease factors are conspiring...

**Comment by joostdecock** [comment]
Well, I guess that's good news. It just means the option defaults and range need to be tweaked, rather than an actual bug.

We'll roll this out in v2.0.2, hopefully no later than tomorrow.

Thank you so much for investigating this so thoroughly, much appreciated

**Comment by GlassSteel** [comment]
By the above logic, Sven looks ok to me on both sites because the old version's fixed ease is about the same as the new version's 8% of my measure, both around 3 inches, good for a knit.

**Comment by joostdecock** [comment]
Good to know. I must have messed up somehow with Simon 🤔
