### ISSUE TITLE
Carlton tail width is incorrect

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#108]
The width of the Carlton coat tail is incorrect. (hat-tip to @SennettTailor for reporting this).

Although the initial complaint was that it was too wide, turns out it's too narrow. 
This is carlton in v2.0.3:

![carlton-wrong](https://user-images.githubusercontent.com/1708494/65014898-46b5a100-d920-11e9-9f5b-88a9ebd9f08f.png)

The key thing here is to understand how the back is pleated, which I've tried to clarify in this image (that already has the fix that will come out in v2.0.4) 

![carlton-right](https://user-images.githubusercontent.com/1708494/65014939-6a78e700-d920-11e9-9a58-308a3b608535.png)

Starting from the left, we go towards the side, fold back on the first fold, then go back until we reach center back again, and fold back on the second fold. This means both folds have cancelled each other out.
The same happens on the right side, so the real width of the tail is the width of the part, with 4 times the distance between 2 fold lines subtracted. In other words, the sum of the values that have been encircled

Note that that last fold line on the right is not actually a fold, it's merely there to indicate where the folded fabric lies on top of the layer underneath.

**Comment by SennettTailor** [comment]
Thanks @joostdecock . Appreciate the prompt response. You are right, the way i imagined the fold of the pleat was different. i was using my imagination and make the ends meet best possible ;)
Your folding instructions above are clear.. i managed to follow and fold..
![IMG_9005](https://user-images.githubusercontent.com/55401821/65034532-d176ba00-d979-11e9-80fc-a92f13acee56.JPG)
![IMG_9006](https://user-images.githubusercontent.com/55401821/65034541-d63b6e00-d979-11e9-9f0a-c7b886cb4de3.JPG)


Looking fwd to v2.0.4

**Comment by joostdecock** [comment]
Thanks for the confirmation @SennettTailor v2.0.4 has been deployed on freesewing.org so you can go there and get the updated version of your pattern.

Tip: You can choose to only print the tail part. Enable the advanced settings (under settings -> advanced).
Then, in the advanced subsection of the settings, set Content to Custom, and only tick the parts.tail box.

Thanks again, and please don't hesitate to raise any issues you might encounter.

**Comment by joostdecock** [comment]
Oh, one more thing. On the actual coat, the box pleat is outwards. So on the paper you folded above, the upper side of the paper would in this case be the inside of the coat.

Just to avoid confusion ;)

**Comment by SennettTailor** [comment]
thanks.

**Comment by SennettTailor** [comment]
Hope all are keeping well. Being locked at home has definitely given the opportunity (or push) to try one of your patterns. I did the first trial with the Carlton after the correction of the tail width. I have few comments and questions:
1. I assume in the attached pattern template: the No.1 and No.2 markings are actually in order to fit correctly the front & back arm pieces. Cant see the corresponding points on the arm pieces. I tried to match the point where the front and back arm pieces join (seam) but can’t. I assume the markings are missing on the pattern (on the arm pieces). 
2. I assume the marking on front bodice No.3 is where the “Back” and “Tail” piece of pattern meets? If this is correct, might be an idea to put a marking on the “Belt” piece (in middle)? 
3. Could not figure out where the corresponding point of the No.4 marker on pattern is (unless it is just a regular point to match the lining?!)
4. I assume the marker No.5 is for collar? – there is no corresponding point on the “Collar” (and/or “Collar Stand”)  
Again, cant simply thank enough to you and the community for your amazing work. 
I have taken notes/pictures on first round – will work on a more pleasing visual ‘instructions” along the 2nd trial and provide a copy for your website. 
<img width="1595" alt="Screenshot 2020-04-20 at 12 05 32" src="https://user-images.githubusercontent.com/55401821/79715127-6a512780-8305-11ea-9823-c77dc2930983.png">
