### ISSUE TITLE
Change mm options in holmes to pct

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1279]
The new changes in Holmes by @bobgeorgethe3rd add two new `mm` options:

 - `headEase`
 - `visorWidth`

I presume that's an honest mistake, as it makes no sense for an ease option to be absolute, and the `visorLength` option is a `pct` option, so surely `visorWidth` should be too.

I'd fix it myself, except I'm not too sure about the defaults to us so I'd rather assign this to BG3.

This blocks out 2.18 release, so tagging it as such

**Comment by bobgeorgethe3rd** [comment]
Fix in c854a97 does not do what was intended by the update.  #1284 will.

**Comment by bobgeorgethe3rd** [comment]
Respectfully, I disagree with this being an issue,
The changes asked here will cause fit and style issues for this pattern.

headEase.
If you change it to pct the ease gets less the smaller the head and more the bigger the head, meaning the hat will become too tight for people with small heads and too loose for people with bigger heads. The ease in this pattern is for accommodating the ear flaps and visors to fit on the head of the person, these components add extra fabric on the sides which needs to be taken into account.The bulk of the fabric does not scale, they are constants based on the width of the fabric. If you ignore this, you have less ease and it will be too tight. At the end of the day, when drafting a hat you do not scale the ease, you would add the required amount for accommodating stuff like ear flaps and visors.

visorWidth
As stated in discord, visorWidth is just a rename of brimWidth that is already mm. I assume the reason Erica chose mm is because again a visor does not scale from person to person, they are constants. For the pct version, I have already had to change the default setting as the visor becomes too small when scaling down. As a fundamental point of drafting you would not draft the visorWidth dependent on the headCircumference. In common hat drafting practices, the visorWidth would be the starting point and the lengths and curves would be dependent on the headCircumference. 

If dolls are the major issue why, the pattern already accommodates for that. headEase option can go down to 0 for this particular reason as well as to get to Erica's default. Erica set the minimum for visorWidth down to 0.5cm, I'm assuming she did this to accommodate for dolls.

I have pct change here  #1284 use them if you want to but I just felt like I needed to state the above first.

**Comment by joostdecock** [comment]
It's ok to disagree. And it's ok to say so. 
Alas, this is an area where I'm not keen to compromise. To quote from [the v3 roadmap](https://github.com/freesewing/freesewing/discussions/1278):

> Using percentage options is the way to go for parametric design, and I will die on that hill.

So yeah, I have strong feelings about this :wink: 

However, I think there's a way out of this because I suspect our red lines are not incompatible:

 - I want percentage options, not millimeter options
 - You want a hat that fits well for everyone with an appropriately-sized visor

Well, guess what, I want that too :slightly_smiling_face: but I am of the opinion that it can be implemented using percentage options.

Practically, I think there's a misconception that percentage options should scale linearly. There's no reason for that.
Yes, it's how things work in the majority of the cases because it's easy to do, but here's no rule about that.

What I would suggest is that you, as the hat connoisseur, figure out what a good amount of ease and a good size of visor would be for this list:

| Model  | Head circumference in mm | Ease in mm | Visor size in mm |
| -----:| -- | -- | -- |
| 1/12 doll |`47` | | |
| 1/8 doll |`70` | | |
|  1/4 doll | `141` | | |
|  1/2 doll | `283` | | |
|  size S woman | `565` | | |
|  size 4XL man | `655` | | |
|  2/1 giant | `1224` | | |
|  4/1 giant | `2448` | | |

If the answer is **it should always be the same** then yeah, we're not going to get to common ground.
But if the answer is **it depends** then tell me what those values look like. 

We'll graph it, implement that in code and voila, everybody happy.

**Comment by bobgeorgethe3rd** [comment]
Yea I don't think we are going to see eye to eye on this. I no longer believe my update to be viable for the website and I don't want to hold up the 2.18 release so I am suggesting to roll back to the original pattern for now so the 2.18 release with Yuri can go ahead.
