### ISSUE TITLE
Increase maximum shoulder slope measurement

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#1700]
**What seems to be the problem?**

The measurement for shoulder slope maxes out at 25 degrees, but a few folks in the Discord have shoulder slopes of 27 degrees or so that they can't input. Maybe shift the max to 30 degrees?

**Additional context**

Discord links: https://discord.com/channels/698854858052075530/757632180980547686/934566268328112128 and https://discord.com/channels/698854858052075530/757632180980547686/934600450039230487

**Comment by nicholasdower** [comment]
Looks like this was last modified in e8ffbf332705ce86dd8c61aef4aa9171b95b9ef4 due to #582, based on a discussion here: https://discord.com/channels/698854858052075530/757632953097388043/760577265988927498

A quick Google search turned up [this study](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.918.7421&rep=rep1&type=pdf) (which I barely read, so take this with a grain of salt please). That contains an interesting chart:
![image](https://user-images.githubusercontent.com/9117775/150672552-1eea1481-d752-4b3d-8b54-4bd5375da34e.png)

The maximum slope found was 34.1°.

Does it make sense to cap the max at 35?

I don't know the implications of this but I'll try it out locally to see whether anything breaks. If not, I'll send a change.

**Comment by nicholasdower** [comment]
Simon with 35°:
![image](https://user-images.githubusercontent.com/9117775/150673098-c165eaad-5214-4ccc-959f-37bdc0ab3493.png)

**Comment by nicholasdower** [comment]
I see 19 patterns which use shoulderSlope. I'm not sure whether it makes sense to have a look at each one. Or maybe there are some key patterns where this change is more likely to cause an issue. Please let me know.

Proposed change here: https://github.com/freesewing/freesewing.org/pull/1557

**Comment by joostdecock** [comment]
I've merged @nicholasdower 's PR for this. Thanks Nick!

While there might be patterns that go off the rails when the shoulder slope goes this high, that's something we should then address in those patterns, rather than cripple the UX by setting a too low limit.

So we'll see how this goes 🤞

**Comment by tangerineshark** [comment]
OMG thank you! This was so fast and so well-thought-out! 🙌
