### ISSUE TITLE
Add deploy preview to pull requests

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1909]
**What is it that you would like to see happen?**

When someone makes a pull request to the monorepo would be great to see autodeploy previews to ensure the pull request is doing what it says it does & doesn't cause any adverse effects

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Example - https://github.com/ONEARMY/academy/pull/159#issuecomment-1037109540

Academy - https://community.preciousplastic.com/academy

Issue generated from conversation here - https://github.com/freesewing/freesewing/pull/1900#discussion_r810468832

**Comment by joostdecock** [comment]
As explained on the FreeSewing contributor call:

- Deploy previews on a pull request are only possible for things inside the repository the pull request was made on. Pull requests on this repo as such can not trigger a deploy preview for freesewing.org which lives in its own repository
- For those website in this repo (like freesewing.dev and in the future freesewing.org) a deploy preview on a PR is possible, however doing a deploy preview for every PR turns out to be rather expensive. In January, we ended up having to pay $42 in build minutes to Netlify because we far overshot our budget of free build minutes. So while deploy-previews are nice to have, they are really expensive as of right now because in a monorepo, there's tons of PRs that are not really related to the website(s)  (as a side-note, none of the projects you link to seem to be monorepos, and PRs on our freesewing.org repo already get deploy previews)
- We have a mechanism for deploy previews which is to do a PR against a specific branch. We might look into a way to do on-demand deploy-previews on the develop branch in the future.

So, closing.
