### ISSUE TITLE
In the side bar, the pattern documentation sub pages are not listed in the same order as on the pattern documentation page

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2025]
**What seems to be the problem?**
When viewing the documentation for a pattern, the pages that are listed in the sidebar on the left are not in the same order as on the main page. I would expect the order to match (i.e. for "what you need" to come after "instructions" in the side bar).
![image](https://user-images.githubusercontent.com/4170521/159792855-28ef5228-0356-48d9-b1bd-4e8bf4caa3d0.png)

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Comment by joostdecock** [comment]
The order in the side bar is alphabetical. The order in the main page is (hopefully) more 'logical'.

I think the right course of action here is to undo/override the alphabetical order in the sidebar.
That would also keep the order consistent across languages, because the alphabetical order is applied after translation:

![Screenshot from 2022-05-15 15-25-24](https://user-images.githubusercontent.com/1708494/168475251-b29a36c8-2ba6-4b3d-b866-ff7f900f13bd.png)

As you can see in the example above, in Dutch the order is different because of translation.

**Comment by joostdecock** [comment]
Cleaning up, but this will be ok in v3.
