### ISSUE TITLE
Detect high chest/shoulder ratio in Brian and (suggest to) draft an off-the-shoulder sleeve for better fit

### ISSUE THREAD

**Issue by woolishboy** [freesewing/freesewing#203]
The drafting method for the armhole doesn't seem to scale well with larger measurements. From some light testing, it seems that it doesn't scale well with biceps circumference and in my case results in an armhole that is at least 50% over ideal and too big to be wearable.

**Comment by joostdecock** [comment]
Can you share your username on the site, and the model you're drafting for. That way I can look into what's going on exactly.

**Comment by joostdecock** [comment]
*copied from chat because it might be useful info to others*

The length of the armhole essentially boils down to two things:

  -  How deep is the armhole vertically
  -  How deep into the back cuts the armhole (horizontally)

It seems like in your case, the main issue is that the armhole is cut too deep horizontally, thereby significantly lengthening the armhole seam.
The reason we draft it that way is because of your shoulder to shoulder measurement which directly controls the across back size (distance between the deepest points of the armholes at the back).

What happens is this: We start from your shoulder point (the top if the armhole) and go down to half the across back measurement (the stationary point of the top of the armhole curve) and then we have to go all the way out to the armhole point.

That's a lot of ground to cover because your shoulder to shoulder measurement is significantly less than what we'd expect based on your chest circumference.
This is not an issue that's specific to FreeSewing. It is a general fitting problem for people with a larger chest.
The way this is typically handled in garment design is to sacrifice the shoulder to shoulder measurement, and instead draft a pattern with a larger shoulder to shoulder, that would thus fall more into the proportions for which the pattern was originally designed.
In practice, what that means is that your T-Shirts, shirts, sweaters, and so on won't have the shoulder seam at the collar point but it will most likely lie beyond the shoulder on the arm (a so-called dropped shoulder).
This way, the armhole doesn't have to travel as much horizontally, and the length of the armhole seam can be kept within reason, so that we can fit the sleeve without too many problems.

At least, that is my read on the situation. As a first step, I would like to ask you to help understand whether this reading is correct.
For that, please could you verify on a woven top (no stretch) where the shoulder seam lies.
Does it like on the tip of shoulder bone like this:
https://www.joemerino.com/pub/media/catalog/product/cache/0ad351a57044898738114f0fc1404561/j/o/joe-shirt-v-coastalblue-shop.jpg
Or does it lie off the shoulder like this: https://images.asos-media.com/products/asos-design-oversized-t-shirt-met-zijsplit-in-beige/11734087-1-humus?$XXL$&wid=513&fit=constrain

So, if my theory is correct (that for a natural looking fit, you'd be better served with an off-the-shoulder sleeve) I would suggest that we try to detect when someone's measurements would justify such an edge-case.

Then, when it does we could:

   - Automatically draft the pattern differently
   - Include some sort of indication that this has happened
   - Allow the user to override this behaviour and draft it the classical way

The good news is that I think we can handle all of this with a plugin. No changes to the patterns needed :)
I'd just like to make sure that this is the correct course of action before seeing whether we can implement it.

**Comment by joostdecock** [comment]
I don't have the bandwidth to roll this into v2.2, so I've set the v2.3 milestone on this.

**Comment by joostdecock** [comment]
We now have the new `raise` method in core (since 2.7.0-beta.2) so we could implement this, than raise a warning telling the user we drafted off the shoulder.

As such, I've added this to the 2.7.0 milestone in the hopes I can fold it into that release :)

**Comment by joostdecock** [comment]
Couldn't fit this in, so I'm bumping this to the 2.8 milestone

**Comment by joostdecock** [comment]
Stale closing. But it was added to our v3 roadmap.
