### ISSUE TITLE
On Windows check for relative path fails on faveicon.ico

### ISSUE THREAD

**Issue by LeviFiction** [freesewing/freesewing#21]
I don't know if there is a better way to handle this. But this worked for my testing.

Add 'example\\public\\favicon.ico' to the template blacklist in the create freesewing pattern package.

REASON:
In the package, Create-freesewing-pattern.  The create-library.js library uses a blacklist set to ignore the faveicon.ico file.

This works on OSX and Linux but on Windows it returns an error 

"Error: Lexical error on line 1.  Unrecognized text"

This appears to be because the command -  path.relative(source, file)  returns Windows style path strings.

In Linux and OSX paths are separated by '/' but in Windows it's separated by '\'.  So when checking if the fileRelativePath is in the templateBlacklist it'll always return false.  Adding the Windows variant to the set takes care of this.

**Comment by joostdecock** [comment]
Thank you for such a detailed issue 👍
I'll fix this ASAP.

**Comment by joostdecock** [comment]
Thanks again for reporting this. I've fixed it. Or at least I think I did, but I don't have a Windows machine, so it's hard to test these things.

The fix is published in [beta-29](https://www.npmjs.com/package/create-freesewing-pattern/v/2.0.0-beta.29), so you can install that version and it should be resolved.

If not, feel free to create a new issue.
