### ISSUE TITLE
Add an option to Simone to ensure a button always falls at the bust apex

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2154]
**What is it that you would like to see happen?**
In order to reduce gaping in shirts of people with breasts (particularly large breasts), it is common to move the buttons so that one button is at the height of the bust apex. This can often require a little shuffing of the buttons to ensure it looks well, so the buttons above the bust point may end up slightly closer together to accomodate the move. 

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

**Comment by SeaZeeZee** [comment]
I may be able to have a look and see how the button placement is done and alter it. It feels like that should be within my capabilities.

**Comment by BenJamesBen** [comment]
A possible fix:
```
% diff designs/simone/config/index.js.orig designs/simone/config/index.js
10c10,15
<     style: [...simonConfig.optionGroups.style, 'frontDarts', 'contour'],
---
>     style: [
>         ...simonConfig.optionGroups.style,
>         'frontDarts',
>         'contour',
>         'bustAlignedButtons',
>     ],
40a46
>     bustAlignedButtons: { bool: true },
```
A new `bustAlignedButtons` option is added, with a default value of true. We're assuming that bust-aligned buttons are usually desired for Simone.

```
% diff designs/simone/src/fba-front.js.orig designs/simone/src/fba-front.js
317a318
>   points.cfBust = new Point(0, points.bust.y)
```
I am not sure whether points.bust or points.realBustPoint should be used. They are slightly different, and I am not familiar enough with FBA-adjusted patterns to know which is better for this purpose.

```
% diff designs/simon/src/shared.js.orig designs/simon/src/shared.js
31,33c31,50
<   for (let i = 1; i <= options.buttons; i++) {
<     points['button' + i] = points[origin].shift(-90, (len / options.buttons) * i)
<     snippets[snippet + i] = new Snippet(snippet, points['button' + i])
---
>   if (options.bustAlignedButtons) {
>     const toplen = points.cfNeck.dist(points.cfBust)
>     const botlen = points.cfBust.dist(points.cfHips) * (1 - options.buttonFreeLength)
>     const toppercentage = toplen / len
>     const botpercentage = botlen / len
>     const topnumberbuttons = Math.ceil(options.buttons * toppercentage)
>     const botnumberbuttons = Math.floor(options.buttons * botpercentage)
>     for (let i = 1; i <= topnumberbuttons; i++) {
>       points['button' + i] = points[origin].shift(-90, (toplen / topnumberbuttons) * i)
>       snippets[snippet + i] = new Snippet(snippet, points['button' + i])
>     }
>     for (let i = topnumberbuttons + 1; i <= options.buttons; i++) {
>       points['button' + i] = points['cfBust'].shift(-90, (botlen / botnumberbuttons) *
>         (i - topnumberbuttons))
>     }
>   } else {
>     for (let i = 1; i <= options.buttons; i++) {
>       points['button' + i] = points[origin].shift(-90, (len / options.buttons) * i)
>       snippets[snippet + i] = new Snippet(snippet, points['button' + i])
>     }
```
To place a button at the bust point, the buttons are split into two groups above and below the bust point. The number of buttons above the bust point is rounded up (and the number below rounded down) to ensure that button spacing above the bust is not larger than below the bust. This might produce odd-looking spacing when a small number of buttons is used, where the top spacing is noticeably different than bottom spacing.

**Comment by BenJamesBen** [comment]
Additional changes to add title and description for the new bustAlignedButtons option. I'm not sure how this works, which files need to be changed and which ones get generated automatically.
```
diff --git a/packages/i18n/prebuild/strings.js b/packages/i18n/prebuild/strings.js
index ccf11a985b..2c7b04c9a0 100644
--- a/packages/i18n/prebuild/strings.js
+++ b/packages/i18n/prebuild/strings.js
@@ -1331,2 +1331,4 @@ export const en = {
   "simon.boxPleatFold.t": "Box pleat fold",
+  "simon.bustAlignedButtons.d": "Place buttons so there is a button at the bust line.",
+  "simon.bustAlignedButtons.t": "Align buttons with bust",
   "simon.buttonPlacketStyle.d": "Style of the button placket.",
diff --git a/packages/i18n/src/locales/en/options/simon.yml b/packages/i18n/src/locales/en/options/simon.yml
index 87e1f00de8..004fa90f40 100644
--- a/packages/i18n/src/locales/en/options/simon.yml
+++ b/packages/i18n/src/locales/en/options/simon.yml
@@ -28,2 +28,6 @@ boxPleatFold:
 
+bustAlignedButtons:
+  title: Align buttons with bust
+  description: Place buttons so there is a button at the bust line.
+
 buttonPlacketStyle:
diff --git a/packages/i18n/src/locales/uk/options/simon.yml b/packages/i18n/src/locales/uk/options/simon.yml
index b4490ebeaa..d435afa736 100644
--- a/packages/i18n/src/locales/uk/options/simon.yml
+++ b/packages/i18n/src/locales/uk/options/simon.yml
@@ -23,2 +23,5 @@ boxPleatFold:
   description: The amount by with the box pleat folds inwards
+bustAlignedButtons:
+  title: Align buttons with bust
+  description: Place buttons so there is a button at the bust line.
 buttonPlacketStyle:
```

**Comment by BenJamesBen** [comment]
(Two code additions in my previous comment were made to the incorrect files, Simon instead of Simone. I'll correct it before the PR.)

This is the what the fix looks like with 4 buttons (plus the extra top button) when using points.realBustPoint vs. points.bust:
![bustAlignedButtons](https://user-images.githubusercontent.com/109869956/180914505-8eccf091-1b9c-49c8-aa0b-355891a13d0d.png)

I've also noticed some weirdness with the placement of the extra top button. You can see this on the existing Simon on freesewing.org if you play with the Design->Style->Closure->Number of Buttons slider. Instead of staying at the top of the garment near the neck, the top button slides down as the number of buttons decreases.

**Comment by joostdecock** [comment]
> Instead of staying at the top of the garment near the neck, the top button slides down as the number of buttons decreases.

The *extra top button* always remains between the last shirt button and the collar stand.

This is expected. It is not the final button of the closure. That one is on the collar stand, not the front.

The docs explain why this button is there: https://freesewing.org/docs/patterns/simon/options/extratopbutton

**Comment by BenJamesBen** [comment]
Thanks for that clarification.

There was another mistake in my first draft fix. Because of floating point math, it would sometimes cause the number of expected bottom buttons to be one too many. The fix for this is:
```
-    const botnumberbuttons = Math.floor(options.buttons * botpercentage)
+    const botnumberbuttons = options.buttons - topnumberbuttons
```

I need to ask Discord:
1. Which to use for the bust line button placement, `points.bust` or `points.realBustPoint` (or something else?).
2. If bust-aligned button spacing should be enabled by default for Simone.
3. What the button spacing strategy should be. 

I have my doubts about the current proposed strategy of different top and bottom spacing. To me, having a shirt with visibly different button spacing seems as if it might be wrong.

Another solution might be to determine the correct top spacing to have a button placed on the bust line, and then simply use that spacing for all buttons. But, that strategy would sometimes cause the bottommost button to be higher than the existing position, perhaps too high in a worst-case scenario with the `topnumberbuttons = Math.ceil(toppercentage)` we're currently using. (In that worst-case scenario, adding another button in the design options would be better, but the customer would not be aware of this.) If we were instead to use `topnumberbuttons = Math.round(toppercentage)` things would work better, causing the bottommost button to be sometimes higher or sometimes lower than the existing position but with the distance it moves being less. Perhaps even the worst-case scenarios would be tolerable.

**Comment by joostdecock** [comment]
My personal preference is to:

- use `realBustPoint` as the location
- do not make this default, because this option can override other options so I geel it should be opt-in
- calculate the correct spacing from neck to bust, then maintain that spacing below the busy so button spacing is equidistant throughout
- override/ignore the *buttonfreeLength* option so you can add all buttons that were requested

This would mean there's no need to split the buttons into 2 groups. It becomes a matter of calculating the button spacing for the top part only, then repeat the same for the lower part.

Feel free to ask on Discord of course, these are just my thoughts on the matter 🤗

**Comment by BenJamesBen** [comment]
Using `points.realBustPoint` and 
```js
  if (options.bustAlignedButtons) {
    const fulllen = points.cfNeck.dist(points.cfHips)
    const toplen = points.cfNeck.dist(points.cfBust)
    const toppercentage = toplen / fulllen
    const topnumberbuttons = Math.round(options.buttons * toppercentage)
    const buttonspacing = toplen / topnumberbuttons
    for (let i = 1; i <= options.buttons; i++) {
      points['button' + i] = points[origin].shift(-90, (buttonspacing * i))
      snippets[snippet + i] = new Snippet(snippet, points['button' + i])
    }
```
We get the following button spacing. The spacing will still be sub-optimal for some numbers, but that's just the nature of how the math works out.
![new button spacing](https://user-images.githubusercontent.com/109869956/181362301-8a6ee348-28dd-40e0-99b8-9f9206772c76.png)

**Comment by joostdecock** [comment]
Go for it. I don't much mind if it's not perfect because I'm not a fan of this option to begin with.

I understand where @TriploidTree is coming from, but I feel that gaping between buttons is a sign of a poorly fitted shirt.

So let's give the people what they want and if they want a 5 button shirt with a button on their bust line, they do it to themselves 🤷

**Comment by joostdecock** [comment]
I am afraid my previous comment was perhaps a bit blunt, I certainly could have phrased it better.

I didn't mean to imply that @TriploidTree doesn't have a valid use-case here, and I certainly wouldn't want to demotivate @BenJamesBen who is being on an absolute streak of great contributions recently.

What I was trying to articulate is that we should not obsess about this option yielding sub-optimal button placement in some configurations.

It's clearly an improvement to have it available, so let's go 🤗

**Comment by BenJamesBen** [comment]
I am still working on this Enhancement request. I have been doing work on it every few days or so, and the code has been "done" for a while. However, every time I test it I discover new issues with my fix that need to be addressed. First, it was the incorrect notch locations on the button/buttonhole plackets. Then, I discovered that my fix broke certain Simon designs. I should be finished with testing and file the PR soon.
