### ISSUE TITLE
Manually Enter Measurements in imperial units

### ISSUE THREAD

**Issue by eriese** [freesewing/freesewing#2246]
**What is it that you would like to see happen?**

I'd like to be able to put in measurements in imperial to save me time converting it all before entering. 

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [X ] No, I am not :thinking:

**Additional context**
The real question is whether folks think it's important to be able to put in fractions. I liked the idea until I started implementing it, and getting the right length of debouncing before formatting seemed like it was going to be a UX issue. Which is to say, I've got code ready to go for this if anyone weighs in on whether they'd prefer fractions or not fractions. Maybe a toggle to turn them on?

**Comment by joostdecock** [comment]
When you say `fractions` doe you mean something like `12.25`? Because you can already input measurements as (imperial) fractions (if by fraction you mean 1/8):

![Screenshot from 2022-06-10 07-52-48](https://user-images.githubusercontent.com/1708494/172999664-61eccb52-eda2-4924-bea7-46cf8bc04fd4.png)

It's not implemented yet in the new measurements input, mostly because I never use imperial :see_no_evil: but obviously it's something we want to support. So perhaps that's what you're referring to?

Anyway, yes we obviously want to support imperial units in all its shapes and forms, but it's not clear to me what measurments input you are referring to. Current website, or future website.

**Comment by joostdecock** [comment]
To be clear: Setting the `mm` state in the example above should also trigger a *save*. By writing to localstorage or sending an update to the backend for example.

**Comment by eriese** [comment]
@joostdecock wait, do you mean?
![sketch viz of joost's method](https://user-images.githubusercontent.com/5298929/173125233-9dd69622-a794-46ec-afa7-aaec1a702d2a.png)

I was doing something similar, but I was also listening to the state, which is where I'm creating the timing issue, but only in the few cases where you're trying to type something like 14 3/16 but it interprets when you've only typed 14 3/1 because that's a valid fraction
![sketch viz of my method](https://user-images.githubusercontent.com/5298929/173126474-ad223010-3a8b-4a02-848d-965b7b619fc7.png)

If you aren't listening to the state, how are you updating the value when it gets changed by, say, pressing one of the preload measurements buttons?

**Comment by joostdecock** [comment]
You've got it all figured out 👍

If you have something like this ready to go, I'd love to see a PR for it.

We can use the units stored in the gist and default to metric for the initial value, right?

**Comment by eriese** [comment]
Wait!

> That's where we're creating the timing issue. I've fixed the problem where your input ends in a decimal, so now I just have two edge cases that are specific to imperial: the one where you're trying to input 14 3/16 but it interprets when you've only typed 14 3/1 so it gets converted to 17 because that's a valid fraction, and the one where you're trying to input 14.55 but it interprets when you've only typed 14.5 so it gets converted to 14 1/2 because it defaults to displaying fractions.

I have a solve for the 3/1 issue, but not the .52 issue


> We can use the units stored in the gist and default to metric for the initial value, right?

yes we totally can and do
