### ISSUE TITLE
Simon(e) placket parts keep all notches from front base

### ISSUE THREAD

**Issue by eriese** [freesewing/freesewing#2399]
**What seems to be the problem?**
Simon(e)'s placket parts have all the notches from the base they inherit from, which creates problems understanding which notches are relevant in a printout

A clear and concise description of the problem you encountered.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [X ] No, I am not :thinking:

**Additional context**

Add any other context or screenshots about the problem request here.
![screenshot](https://cdn.discordapp.com/attachments/757632953097388043/996183411800678510/unknown.png)

**Comment by eriese** [comment]
It's also happening with the bnotch on the split yoke

**Comment by BenJamesBen** [comment]
7 notches are inherited from front.js. The buttonhole placket uses 3 of these notches, but the rest are superfluous. The button placket uses none of the notches. A possible fix in designs/simon/src:
```
% diff buttonplacket.js buttonplacket.js.new
29a30,32
>   for (const i in snippets) {
>      if (i.indexOf('notch')) delete snippets[i]
>   }
% diff buttonholeplacket.js buttonholeplacket.js.new
27a28,30
>   for (const i of ['waist', 'armholePitch', 'hips', 'armhole']) {
>     delete snippets[i + '-notch']
>   }
```

The split yoke bnotch is not inherited from the base. Instead, it is explicitly added in yoke.js. For this reason, I assume that the bnotch might be intentional but perhaps the location is simply incorrect? (I'm not sure what this bnotch's intended purpose is.) In designs/simon/src/yoke.js:
```
   if (complete) {
     ...
     if (options.splitYoke) {
       snippets.sleeveNotch = new Snippet('bnotch', points.armholePitch)
     }
     ...
   }
```

**Comment by joostdecock** [comment]
Hey @BenJamesBen would you like to submit a PR for this? Since you've already got it figured out?

**Comment by BenJamesBen** [comment]
@joostdecock Yes, I will submit the pull request for this fix, once I get familiarized with how things work and what other supporting file changes are needed. I haven't used git or Github before, so I am learning how branches work.

Regarding the stray sleeveNotch bnotch that appears when using a split yoke, is it intentional and in the incorrect location? If so, I do not know what its correct location should be. If instead it isn't needed, I can simply remove it.

**Comment by BenJamesBen** [comment]
![Split yoke bnotch](https://user-images.githubusercontent.com/109869956/180911607-6522334a-6704-49e7-9d6b-bfebb2b7dd0c.png)
The split yoke bnotch.

**Comment by joostdecock** [comment]
No, that's an oversight.

The yoke is based on the back part which has these notches in it.
So we forgot to clean it up.

God catch 👍
