### ISSUE TITLE
Yoke piece has issues in the bottom corners when you add box pleat.

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2400]
**What seems to be the problem?**
When generating a Simone with my dimensions, the corners of the yoke appear malformed. 

Initially found in the lab, happens on main site too. Seems to occur on "box pleat : yes"

![image](https://user-images.githubusercontent.com/4170521/178526789-161e4f20-eded-43c0-a32a-3e643e66cdec.png)
![image](https://user-images.githubusercontent.com/4170521/178527878-d21ae973-3b65-4ca9-a74f-eaa29d8f0fc5.png)

https://gist.github.com/TriploidTree/16cc1d8d23e10579a27a6c454e85492d

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

**Comment by BenJamesBen** [comment]
The same issue also seems to occur with Simon, and I think that the problem is with the Simon pattern. In back.js a number of points including armholeYokeSplit are shifted over when there is a box pleat to make the back piece wider. However, yoke.js seems to need to use the original armholeYokeSplit point. Similarly, the notch in back.js also needs to use the original point, I think.

A possible fix, in designs/simon/src:
```
% diff back.js.orig back.js
130a131
>   points.armholeYokeSplitOriginal = points.armholeYokeSplit
211c212
<     snippets.sleevecapNotch = new Snippet('notch', points.armholeYokeSplit)
---
>     snippets.sleevecapNotch = new Snippet('notch', points.armholeYokeSplitOriginal)
% diff yoke.js.orig yoke.js
10c10
<   paths.saBase = new Path().move(points.cbYoke).line(points.armholeYokeSplit)
---
>   paths.saBase = new Path().move(points.cbYoke).line(points.armholeYokeSplitOriginal)
```

I am not familiar with how Simon/Simone was designed, so I don't know if my fix might have any unintended side effects.

**Comment by joostdecock** [comment]
Thanks @BenJamesBen how's #2471 for a fix?

**Comment by BenJamesBen** [comment]
I tested your fix in lab and confirmed that it works. Did you want me to review and approve the changes in Github? (I am not really familiar with either Javascript or the freesewing codebase to know what changes are proper or needed.)

**Comment by joostdecock** [comment]
You have to see this as me trying to make you part of the process so you feel welcome and encouraged to keep contributing :wink:

You are free to review any PR, in this case, I'm happy to just push it through because I'm pretty sure it's fine (Simon is my design after all).
