### ISSUE TITLE
No confirmation email when signing up

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#2446]
**What seems to be the problem?**

A Discord user (Geordie) reports not getting the confirmation email from FreeSewing, details here: https://discord.com/channels/698854858052075530/698854858496802868/999123677058707519

**Comment by GeordieGuy** [comment]
Hullo, I'm the aforementioned Discord user. When I signed up there was a notification that a confirmation email would be sent, it never arrived. In the weeks since then I've periodically tried the re-send button to no effect, and tried different email clients on the chance there was some filter or other feature obscuring the email. It's not in the junk folder or deleted items.

**Comment by joostdecock** [comment]
Email sent. Probably blocked by the provider. Provided user with activation link out-of-band. Closing
