### ISSUE TITLE
Bug report: When restarting the dev/design environment setting are remember, but the menu returns to default settings

### ISSUE THREAD

**Issue by SimonbJohnson** [freesewing/freesewing#2448]
**What seems to be the problem?**

If you have seam allowance setting turned to yes and then restart the dev server the seam allowance is still rendered, but the menu has been reset to default settings e.g. seam allowance = no
**Are you a FreeSewing patron?**

Yes, I am :hugs:

**Additional context**

<img width="845" alt="Screenshot 2022-07-20 at 14 39 44" src="https://user-images.githubusercontent.com/2110742/179997379-8c187010-c967-4d4d-8c84-305a345228b5.png">

**Comment by eriese** [comment]
@SimonbJohnson I was seeing that problem a while ago, but I'm not able to reproduce it on the latest development branch. Can you confirm that you are up to date with `develop`?

**Comment by SimonbJohnson** [comment]
@eriese - This is what I pulled down two days ago, if this helps?

  "dependencies": {
    "@freesewing/config-helpers": "next",
    "@freesewing/core": "latest",
    "@freesewing/plugin-bundle": "latest",
    "esbuild": "^0.14.49"
  },
  "devDependencies": {
    "@freesewing/plugin-svgattr": "latest",
    "@freesewing/plugin-theme": "latest",
    "@freesewing/plugin-i18n": "latest",
    "@freesewing/utils": "latest",
    "@freesewing/models": "latest",

**Comment by eriese** [comment]
@SimonbJohnson Sorry, I thought I replied to this days ago!

This issue is fixed in `develop`, so whenever the next build is, you should be sorted. Given that you've indicated that you're using freesewing libraries in an external tool, it probably makes sense for you to keep using `latest` because we make no guarantees for the stability of what's in `develop`. However, if you'd like to have the fix immediately, you could always have your dependencies point to `develop` instead

**Comment by SimonbJohnson** [comment]
Great, closing this!

**Comment by joostdecock** [comment]
@all-contributors please add @SimonbJohnson for bugs

**Comment by eriese** [comment]
It does, thank you!

This issue is fixed in `develop`, so it should be out with the next
release.

If you want it now you could of course have your dependencies pull from the
branch instead of the published packages, but things move very quickly in
`develop` and there's no guarantee it won't be broken in other ways, so
it's really up to you which makes more sense for your project.
