### ISSUE TITLE
[docs]: Document new methods in core

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2468]
### What is it that you would like to see happen? 🤔

Document the following methods:

- [x] part.addCut
- [x] part.removeCut
- [ ] part.setGrain
- [ ] part.setCutOnFold
- [ ] path.setClass
- [ ] point.setText
- [ ] point.setCircle
- [x] pattern.getCutList()

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by joostdecock** [comment]
Working on this now, so I've added checkboxes and self-assigned this.

**Comment by BenJamesBen** [comment]
- [x] ~~part.setGrain~~
- [x] ~~part.setCutOnFold~~
- [x] path.setClass
- [x] point.setText
- [x] point.setCircle

Since this bug was filed, documentation was added (fulfilling tasks) and the core has changed (eliminating tasks). All the tasks in this bug have been addressed, and the bug can be closed.
