### ISSUE TITLE
Unable to create an account via Oauth

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing#26]
1. Sign up with either github or google

## Expected Behavior

It to sign me up

## Actual Behavior

It gives an error:

`https://backend.beta.freesewing.org/callback/from/google?state=5d2e72879b4ac16f227ba9dd&code=4/iQGXKkUQu4aL-dPUZzyz4lu6XL9_tVplHLT2sKCHZNstlBbQCtlacCoaf4LCzBMDTA6mDpbpj9P3FROaWLj7I-I&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=occsn.com&session_state=b011a3aa2f8a8d8bf5e3f846f179a1cf34e0a71b..c8f4&prompt=none`

`Internal Server Error`

**Comment by joostdecock** [comment]
You're using beta.freesewing.org which has been superseded by en.freesewing.org.
That being said, we haven't implemented Oauth there (yet) but it's no surprise that this doesn't work.

We should get rid of beta.freesewing.org, as we're still working on the new site, we sometimes refer to it, which is why we keep it around.

If you want to try the new site, go to en.freesewing.org. Docs are at freesewing.dev
