### ISSUE TITLE
Unable to sign up, and login after email confirmation

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing#27]
1. Sign up with new email and password
2. Click confirmation in email

# Expected

To be able to login on website

# Actual

Gives an error:

`Authentication failed`

## Notes: 

https://beta.freesewing.org/confirm/signup/5d2e5cc89b4ac16f227ba9dc

**Comment by joostdecock** [comment]
You're using beta.freesewing.org which has been superseded by en.freesewing.org.

We should get rid of beta.freesewing.org, as we're still working on the new site, we sometimes refer to it, which is why we keep it around.

If you want to try the new site, go to en.freesewing.org. Docs are at freesewing.dev
