### ISSUE TITLE
[feature]: Add HPS to shoulder measurement

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2850]
### What is it that you would like to see happen? 🤔

AMJ writes [on Discord](https://discord.com/channels/698854858052075530/788055816011251722/1022303276336676884):

> Is this a good place to request an additional measurement in the next version - neck to shoulder? Just asking because it's something I always have to adjust manually. Don't know how helpful it would be to others.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

Perhaps we can/should add this as an optional measurement. If nothing else, it will prevent breaking patterns that extend our blocks.

**Comment by BenJamesBen** [comment]
In today's May 27, 2023 Contributors Call, we decided to address this issue by adding a new option to our designs to modify neckholes, rather than add the new measurement. The new option will help customers who find that they need to modify patterns that produce neckholes that do not work for them using existing measurements (of neck circumference and shoulder-to-shoulder).

**Comment by joostdecock** [comment]
> In today's May 27, 2023 Contributors Call, we decided to address this issue by adding a new option to our designs

Did we? Then I guess we can close this.
