### ISSUE TITLE
[bug]: [Paco] Including Back Pocket parts results in multiple Back parts shown

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2878]
### What seems to be the problem? 🤔

In the v3 localhost lab for Paco, in Contents/Only if the `paco.backPocketBag`, `paco.backPocketWelt`, or `paco.backPocketWeltInterfacing` parts are selected, another Back part is shown in the DraftDesign layout. 

![Screen Shot 2022-09-28 at 10 19 22 AM](https://user-images.githubusercontent.com/109869956/192858980-20a67c76-84ee-492a-adb2-e926282fc764.png)

This behavior is not seen in lab.freesewing.dev. Instead, the Back part is shown only when the Back part is selected. Nothing is shown for the Back Pocket Bag, Back Pocket Welt, and Back Pocket Welt Interfacing parts.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
This was fixed earlier today in a commit that fixed suppression the visibility of nesting dependencies.

**Comment by BenJamesBen** [comment]
Re-opening. I am still able to reproduce this behavior as of 911ada1606f7eae65e493195db262d7cc6e33df1.

Steps to Reproduce:
1. In the `develop` localhost lab, go to the Paco design and select any Size.
2. In Settings -> Contents, select these 4 parts to include: `paco.back`, `paco.backPocketBag`, `paco.backPocketWelt`, and `paco.backPocketWeltInterfacing`.
3. Observe that 4 Back parts are seen.

**Comment by joostdecock** [comment]
Hmm, this is tricky.  The user's choices override the hiding of parts. Like, when you say (in Paco) give me `titan.front` it will be included, even though that part is hidden.

Same thing happens here, you force visibility of the part. But unless the back pocket option is enable, that part will simply set itself hidden and return. But because it inherits from the back part, you see an extra back part.

It's not really a bug from that point of view, but I guess it is somewhat unexpected. So I will refactor Paco to deal with it.
