### ISSUE TITLE
[bug]: "count:" option values are strings instead of numbers

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2897]
### What seems to be the problem? 🤔

When changed in the UI, `count:` options are strings instead of numbers, and I don't think that is the intended behavior.

This is causing problems, for example in PluginTest when the Dimension -> dimensionD setting is changed it results in an error because `Called Path.offset(distance) but distance is not a number`.

According to inspection via `typeof()`, options.dimensionD starts out as a "number", but after changing the value in the UI it becomes a "string".

```js
  options: {
     dimensionD: { count: 10, min: -20, max: 20, menu: 'dimension' },
   },
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This bug is seen in both the `develop` localhost lab and lab.freesewing.dev.

This bug also causes a PluginTest error when changing gore -> goreExtraLength. A workaround is to change the design code `plugin-gore.mjs` to cast the value to an integer:
```diff
@@ -8,7 +8,7 @@ const pluginGore = ({ points, Point, options, macro, part }) => {
       from: points.start,
       radius: options.goreRadius,
       gores: options.goreGoreNumber,
-      extraLength: options.goreExtraLength,
+      extraLength: Number(options.goreExtraLength),
     })
   }
```

**Comment by joostdecock** [comment]
Hmm, this is a bit tricky because as soon as you hit the level of HTML attributes, everything is a string.
And while we can probably handle this in the frontend Javascript code, I think the more charitable way to go here is to make core handle the conversion, and those plugins where it's relevant.

So that's what I've implemented. And that should fix it. If not, please re-open.
