### ISSUE TITLE
[bug]: Development environment does not ship with prebuild translation files (Error: Default namespace not found at public/locales/en/common.json)

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3267]
### What seems to be the problem? 🤔

When spinning up the development environment, it throws an error:

**Error: Default namespace not found at public/locales/en/common.json**

It seems that we're not shipping the pre-build translation files.

### Design / Plugin / Package 🧐

packages/new-design

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

See PR #3268 for this

**Comment by eriese** [comment]
I think it might be due to this: https://github.com/freesewing/freesewing/commit/ad148eb59dedad7c483df5dfb393c94c96c34f2b#diff-1d42aaeda0f4874eb7852e37861d6c520dea972c722c5e13d080f022ad4c6e83L66

We used to build the package and run the `bin` from `dist`, but now we just run the script. Which I approve of, but means we're going to need to run that i18n prebuild step at runtime

**Comment by eriese** [comment]
Not currently seeing this when running `npx @freesewing/new-design@next` for `brian`, `scratch`, or `tutorial`
