### ISSUE TITLE
[docs]: Improved freesewing.dev layout and content

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3386]
### Suggested content

We need documentation about the source code, what things/features are found in what directories, what everything is, how things work. How the app works, in broad terms. 

A guideline for new code contributors documentation.

Example: How does search work? What is Algolia, where is the script, what does it do, when does it run?

Example: What is Node.js, Next.js, React? What do they do for us, In general terms? What is MDX, and how is it used in FreeSewing? Strapi and i18n? Husky? Prettier? Remark? Rehype?

Example: What are the different FreeSewing websites, lab, dev, posts, backend, sanity, etc., and what do they do?

Example: What is Yarn? Terraform? Eslint? Ansible? Lerna?

Example: What are the FreeSewing packages? How are the published? How do you get different versions? How do you determine the latest published version?

Example: How do you add new Contributors to the list?

Example: How do the org and dev sites get updated? How to find the current versions in GitHub (if this is even possible)?

Example: What are the other GitHub repositories owned by FreeSewing and what do (or what did) they do? 

Example: What is the "workbench"? What is a "lightbox"? What is a "worm"? What is a "slug"?

Example: How do the README and package.json files get updated? (from config) How does publishing work?

Example: What do all the scripts in the `/scripts` directory do?

Example: How does the newsletter get published/sent?

Example: What is that `exceptions.yaml` file, and why is it used?

Example: How do the tests work? How do you write/add/edit tests?

Example: What is that Vercel? How do ordinary people without Vercel accounts use it? 

Example: What is Deepscan? What should you do if it finds an error when you submit a PR?

Example: How does Crowdin work, on the FreeSewing side of things? How is it integrated into FreeSewing after the Crowdin users do what they do. Same with Strapi.

Example: How is GitHub configured? How to edit templates? How are GitHub Issues automatically created via the FreeSewing websites?

Example: How does the lab UI work? Where do you go to make changes?

Example: How is eslint configured? How do you make changes to the rules it is following?

Added: Open Graph

**Comment by eriese** [comment]
Hey @BenJamesBen can you please clarify, are you requesting centralized documentation on all of this? Or are you saying that things are under-documented in place?

**Comment by joostdecock** [comment]
Does this PR come with a team of documentation writers? 😋

I'm in favor of great documentation, but I feel the scope here is extremely wide.

With some things being rather niche (what is Ansible?) And others very generic (What is Node.js, Next.js, React).

We're rather far into coding bootcamp territory here, and I doubt we have the bandwidth fir that. So I'd prefer to focus on what's FreeSewing specific.

I think it's perhaps worth to point out my comment about mentorship here: https://freesewing.dev/howtos/ways-to-contribute

There's entire websites and even businesses devoted to explaining to people what Node.js is (for example). It's a noble goal, but it doesn't make for a compelling value proposition.

**Comment by eriese** [comment]
I'm with Joost that this is an admirable motivation on your part, but as you speak about a hope to keep people from wasting effort, I want to dig into some of it in the hopes that I can help you put your energies to the most constructive parts of this.

I love a contributor setup guide and think it's very useful to have step by step instructions on how to get your environment going so you are able to work with the repo you're trying to contribute to. Thankfully we have such a setup guide because contributing on the pattern design level and contributing on the infrastructure level require the same setup. 

I am also in favor of giving folks a little tour of how all our moving parts come together. 

I do not think explaining to people how to write a lint config or how to change our github templates is useful. Those are both things that I think being able to find the docs yourself is an appropriate barrier to entry for messing with them.

However, I do I think explaining why things are configured the way they are can be done with inline documentation (which I agree we could definitely improve) and README's (which already exist in most of the folders listed here for explanation), or custom tooling. For instance, instead of a document that I'd have to go read, I'd rather add a pre-install hook that warns people that they're adding a dependency directly to a `package.json` but that it's going to be clobbered on the next reconfigure and they need to put it in `dependecies.yaml`. As a developer, it's not likely to occur to me to check the docs about something like dependency management, so I need to be informed in place. 

The further away from the actual code the documentation is, the less useful it becomes, so I'm in favor of better comments on our internal code and using a tool like https://www.naturaldocs.org, or even JsDoc to compile those into docs, which is a very standard way for developers to learn how a codebase works.  This would encourage documenting our internal code more thoroughly in the code files because that'll be automatically converted to searchable documentation. Maybe there's some tool that'll make you a wiki out of all the READMEs in your repo, and that could be useful for helping people understand what all the packages are.

Regarding the three potential users and their use cases
> **The beginning code designer:** ....

I think perhaps a disconnect here is that even an employee of a company with a large code base does not expect to be presented with the level of documentation that you are suggesting. I also am not on board with the idea of open source participation as a job in any way. Open source participation is ad hoc. Our main use case for a beginner coder coming here to contribute is that they want to write a pattern (which we have extensive documentation on how to do) or that they found a bug they can already see a way to fix. You learn a project over time, or you do the one thing you wanted to do and you move on. 

> **The advanced code designer:** ....

As an experienced developer, I already know that `slug` is the term for a file path. Yes, coder jargon is obnoxious, but if you're going to get to an advanced level you're going to pick it up. Since joining this project I have learned that this jargon is apparently international. Also as an experienced developer who does a lot in a lot of places in this repo, I've never looked at what Algolia does for us and if I wanted to know more about it, I'd go read the Algolia docs. As mentioned above, I like a bit of centralized API documentation, but I also do not think it's a waste of time for an advanced developer to familiarize themself with the code by reading it.

> **The general public:** ....

People who we expect to not read the docs cannot be the most important people to write the docs for. And if they were, I would imagine that our current massive docset would put them just as at ease as an even more massive docset because how will they know the difference? 

> I feel that this documentation is the most important thing for me to be doing at this moment to help the FreeSewing project with its long-term success.

Even if under documentation was the downfall of those platforms, it doesn't necessarily mean that we are under-documented to an offputting degree. I want to point out that a major difference between seamly/valentina and us is that they do not offer any stock patterns, and the process of pattern design in those programs doesn't involve code. This means that the overlap between their developers and their pattern designers was probably a lot smaller, which I can imagine would make non-developers feel less able to get involved and make the pattern designer community feel like they were out on their own making their own resources. 

As far as I can tell, even with larger open source communities, the number one reason an open source project dies is because its primary maintainer stops having time for it. No matter how many other people you can attract to doing *some* of the work, there are very few people you can convince to take on the *bulk* of the work, so it's very hard to find someone to hand it off to. It's true that being able to attract a larger number of skilled developers has the chance of taking some of the burden off of Joost, which has the chance of keeping him from burning out, so I think it will be beneficial to look back through this list and really prioritize the ones that will feel important to that group

**Comment by eriese** [comment]
Possibly an interesting tool to help reach the over arching goals of this issue: https://www.codesee.io/open-source-hub

**Comment by eriese** [comment]
One person's exhaustive guide on how to do effective architecture documentation: https://www.workingsoftware.dev/software-architecture-documentation-the-ultimate-guide/

**Comment by BenJamesBen** [comment]
A proposed organizational structure for the FreeSewing.dev website. This structure more naturally accommodates the documentation additions I would like to add.

FreeSewing.dev:
- For all Developers
- For Pattern Designers and Coders
- For Infrastructure Coders
- For Writers
- For Translators
- How to work as a team and as part of a greater community
- About FreeSewing
- Development Blog

---

- For all Developers
  - Lab UI documentation
  - Getting Started
    - Linux tutorial
    - Mac tutorial
    - Windows tutorial
    - Gitpod Tutorial
    - Codespaces Tutorial
    - Vercel Tutorial
  - Using the development environment
    - yarn kickstart
    - yarn lab to start the lab dev environment
    - cd sites/dev ; yarn start to start the dev website dev environment
    - cd sites/org ; yarn start to start the org website dev environment
    - Using web browsers (clear cache, cookies, local storage; using Javascript console)
    - yarn clean
    - npm rebuild sharp
    - ? Node and nvm? How to change node versions?
  - The `freesewing/freesewing` repository.
    - Map/tree showing overview of where files are located
    - What files get generated automatically, and what files do you edit instead?
  - Basic workflows
    - Keeping your repository up-to-date
    - Dealing with git pull conflicts
    - Using branches to organize changes
    - Running lint
    - Testing changes with `yarn test`
  - Git
    - Basic concepts: repositories, commits, branches, etc.
    - Quick reference
    - Common git challenges
      - Adding files
      - Moving files
      - Deleting files
      - Merging conflicts
      - Diffing files
      - Viewing history
    - Git Training
    - Useful advanced tricks (aliases, config, replacing commit messages)
  - GitHub
    - Account basics
      - How to set up and use those security login tokens.
    - Working with PRs
      - How to submit PR
      - Dealing with with PR problems
        - Test failures
        - Lint failures
        - Deepscan failures
        - Merge conflictss
      - How to review a PR (including viewing Vercel deployment, if available)
      - How to make requested changes to a PR and resubmit
      - Working with Draft PRs
      - GitHub labels and the PR state workflow.
    - Working with Issues/Bugs
      - How to file a bug (including best practices)
      - How to work on a bug
    - Working with Discussions
    - GitHub Tutorial
    - FreeSewing's GitHub configuration and integrations. The other freesewing repositories.
    - Finding what you want. (How to search, how to filter views, , using the Project pages, etc.)
  - ?SVG?
    - ?SVG basics?
  - Other useful information
    - How to add new Contributors.

---

- For Pattern Designers and Coders
  - Before you start (SVG, coordinates, units, Béziers)
  - Pattern design tutorial
  - Design submission process (how to submit new designs to FreeSewing)
  - Pattern concepts guide (sets, stacks, parts, points, etc.)
  - Reference
    - Core API
    - Macros (includes Plugins)
    - Snippets (includes Plugins)
    - Other Plugins (svgattr, theme, versionfree-svg, timing, i18n)
    - Measurements
    - Settings
    - CSS classes
  - Common Pattern Design and Coding challenges and howtos
    - How to actually add translation text, after including translation keys in the pattern.
  - Common Pattern Documentation challenges and howtos
    - How to write documentation for new designs.
    - How to add the initial translation files for new designs.
    - How to generate those options images.
  - Pattern design best practices
  - Pattern design Frequently Asked Questions
  - Best practices for design code reviews, howto

---

- For Advanced or Infrastructure Coders
  - Overview of how FreeSewing works (backend, posts)
  - Technologies used (Algolia, OpenGraph etc.)
    - Node.js, Next.js, React, MDX, Strapi, Husky, Prettier, Remark, Rehype, Sanity, Terraform, Eslint, Ansible, Lerna
    - Nx
    - Concepts. (workbench, lightbox, worm, slug)
  - The various *.freesewing.* sites.
  - FreeSewing Backend API
  - Lifecycle hooks
  - Freesewing's packages
    - Package documentation
  - Plugin guide
  - ? Deploying FreeSewing as a node app?
  - ? Generating patterns with a browser?
  - Writing tests. Playwright. Chai Expect.
  - FreeSewing's release process and workflow
    - How do the org and dev sites get updated?
    - How do you find the current version in GitHub?
  - The package.json commands and /scripts. What do they do?
  - How does the newsletter get published/emailed?
  - Infrequently Asked Questions
    - What is that `exceptions.yaml` file, and how is it used?
    - How is prettier configured?
    - How is eslint configured?

---

- For Writers
  - CSS classes
  - Common Editing challenges
  - Markdown Guide
  - Style Guide
  - How to make SVG illustrations for the website.
  - Strapi Guide/tutorial
  - Sanity Guide/tutorial
  - How to submit an edit to a documentation page (for contributors who want to help change documentation but who don't want to learn git or GitHub)
  - Best practices for documentation reviews
  - How to add a showcase?
  - A brief summary of the translation workflow that occurs after a documention change/addition is made. This is so people are aware of what happens.

---

- For Translators
  - ? The translation process/workflow. A more detailed description for the people actually working on translations.
    - Including the Crowdin PRs process
  - ? Crowdin
  - ? Strapi
  - ? Translation Guide
  - ? i18n strings: location of files, how to edit

---

- How to work as a team and as part of a larger community
  - Communication
    - Modes: Discord. GitHub reviewers. Tagging people on GitHub.
    - Make sure to communicate: after filing a bug, before closing a bug, after filing a PR.
  - Collaboration
    - Using Discord voice chat.
      - Sharing screens.
  - Consensus
  - Stakeholders
    - Identifying who the stakeholders are.
  - No middle managers

---

- About FreeSewing
  - How to contribute (the developer-facing ways) (Or, should this just be on org?)
  - Code of conduct (actually, this should be on the org site. Or both sites?)
  - Community standards (from org. another item that should be on both sites?)
  - Licenses, copyright, and Open Source notices (another on both site?)
  - Sponsors (another on both sites?)

**Comment by joostdecock** [comment]
@BenJamesBen Is there any way we can find some middle ground here? The list you have included above is very long and almost certainly contains things that are out of scope (for example, it's not our job to explain Github, they have excellent documentation themselves).

I'm happy to try to improve/restructure things. But I feel we need to set a goal that is attainable. 

I feel there's really two things here that come into play:

- Things that are currently not documented and we'd like to see that changed
- Documentation structure

For the first one, I think it's pretty clear that we'd like to see more documentation. But I do not feel it's all that useful to keep an issue open for that.

For the second one, I don't think constantly moving markdown files/folders around is all that useful. The current problem of "is it a guide or is it a how-to" will only be replaced with "is it for advanced coders or for all coders".

Currently, the documentation structure is tightly linked to how we present the navigation. However, with the new v3 UI that is no longer the case (I mean, it is but we can override things).
So I personally feel that what would be a great improvement is to create different *entry points* for different roles/purposes.

To  facilitate that, I've added some functionality to the `ReadMore` component as well as added a new `DocsTitle` component (this allows to include the title of another page without having to maintain it in 2 places or translate it).

That work is in #4096 and I have created an example which you can see here: https://freesewing-dev-git-joost-freesewing.vercel.app/design

If you compare it to the page's source, I hope you'll find this is an elegant way to sort of create a thematic *view* on the available documentation.
I don't think this conflicts with your work in #4097 as that is more about writing documentation that's missing, but I muse admit I was a bit blindsided by this as I had this in the works for a while but had issues getting the build to pass.

Anyway, let me know what you think whether you think we can proceed somehow. I'm happy to discuss things on the call, but I'm reluctant to put all documentation work on hold while we wait for that. Especially since between you and me we cover 99% of the docs on FreeSewing.dev :shrug:

**Comment by BenJamesBen** [comment]
@joostdecock I'm trying to understand what you are proposing:

- As I understand it, #4096 keeps the existing tutorials/guides/howtos/reference directory structure, correct?
- The change is that there is now an additional navigation structure that is not bound to the directory structure? And, this new navigation structure gives us the flexibility to present a logical organization for topics, regardless of where files are in the directory structure?
- So, in the new navigation structure, there would be a place for an entry into the Writers Guide, and the actual Writers Guide files would be located in `/guides`?
- And, we could leave the Markdown Guide files where they currently exist, but still have them under the Writers Guide hierarchy in the new navigation if we wanted to?
- And, the new navigation would have a place where the Getting Started tutorials would be linked, but the actual Getting Started tutorial files would remain where they currently are under `/tutorials`?

(I disagree that GitHub is out of scope for our documentation. You are correct that it isn't our job to explain what GitHub is generically. However, I feel that we need to explain how to use GitHub in the context of the FreeSewing project: What are our workflow expectations for how our contributors use GitHub. What FreeSewing-created labels exist and how/when to use them. How we want people to name bugs and PRs. Etc. And, I also think that having quickstart tutorials and cheatsheets for common procedures would also be beneficial.)

**Comment by joostdecock** [comment]
@BenJamesBen 

> As I understand it, https://github.com/freesewing/freesewing/pull/4096 keeps the existing tutorials/guides/howtos/reference directory structure, correct?

Correct

> The change is that there is now an additional navigation structure that is not bound to the directory structure? And, this new navigation structure gives us the flexibility to present a logical organization for topics, regardless of where files are in the directory structure?

Correct

> So, in the new navigation structure, there would be a place for an entry into the Writers Guide, and the actual Writers Guide files would be located in /guides?

Correct

> And, we could leave the Markdown Guide files where they currently exist, but still have them under the Writers Guide hierarchy in the new navigation if we wanted to?

Yes, on the page at least.

> And, the new navigation would have a place where the Getting Started tutorials would be linked, but the actual Getting Started tutorial files would remain where they currently are under /tutorials?

I'm not saying we can't move things around. But I am saying that no matter where you move them, some things will always be something that should arguably be in two places for easy discovery. So let's not make the file structure on disk the only way to organize things

> I disagree that GitHub is out of scope for our documentation. 

I'm not going to stop you from writing that documentation :)

**Comment by BenJamesBen** [comment]
I'm fine with your PR #4096 layout for the dev website files.

I can close this Issue #3386, and Issue #3331, and Issue #3392 (though I'll probably copy/move some of their content into Discussion #3988 (the org website layout discussion, recategorizing the discussion to be for things we want to include on our websites, writing them down so we don't forget).

**Comment by joostdecock** [comment]
Sounds good. I also consider how we do things in `.dev` to be a testing ground for how we'll do things in `.org` so it makes sense to keep things in that context.

**Comment by BenJamesBen** [comment]
Closing. The task and contents were merged into Discussion #3988.
