### ISSUE TITLE
[bug]: Some Snippets do not obey pattern scaling

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3579]
### What seems to be the problem? 🤔

Some Snippets like buttons, buttonholes, notches, bnotches, and bartacks do not change size when the overall pattern scale setting is changed. Others like the logo do scale.

Steps to Reproduce:
1. In the localhost lab development environment, using the Simon pattern, select cisFemale Doll 10% size, and go to the DraftDesign view.
3. Observe that some graphical elements are large.
4. In the Settings menu on the right, change the Scale setting to 0.1.
5. Observe that most graphical elements get smaller.
6. However, also observe that the notches, bnotch, buttons, and buttonholes did not get smaller.
7.  Move the Scale setting slider back and forth, and observe that while other elements shrink and grow, the buttons, buttonholes, etc. remain the same size.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
The logo is a special snippet in that it scales itself. Other snippets like buttonholes don't scale themselves and instead depend on the core infrastructure to scale them.

A possible fix for the issue in exported SVG/PDFs is:
In `packages/core/src/svg.mjs`:
```diff
@@ -322,7 +322,7 @@ Svg.prototype.__renderSnippet = function (snippet) {
   let x = round(snippet.anchor.x)
   let y = round(snippet.anchor.y)
   let scale = snippet.attributes.get('data-scale') || 1
-  scale = scale * (this.pattern.settings.scale || 1)
+  scale = scale * (this.pattern.settings[0].scale || 1)
   if (scale) {
     snippet.attributes.add('transform', `translate(${x}, ${y})`)
     snippet.attributes.add('transform', `scale(${scale})`)
```
A possible fix for the issue in the lab UI is:
In `sites/shared/components/workbench/draft/snippet.mjs`:
```diff
@@ -51,7 +51,8 @@ export const Snippet = (props) => {
     x: props.snippet.anchor.x,
     y: props.snippet.anchor.y,
   }
-  let scale = props.snippet.attributes.get('data-scale')
+  let scale = ( props.snippet.attributes.get('data-scale') || 1)
+  scale = scale * (props.gist.scale || 1)
   let rotate = props.snippet.attributes.get('data-rotate')
   if (scale || rotate) {
     snippetProps.transform = ''
```

**Comment by BenJamesBen** [comment]
Bartacks are Macros not Snippets, so they are not a part of this bug and should be fixed separately. 

However, macros are responsible for scaling themselves, and a possible fix might be:
In `plugins/plugin-bartack/src/index.mjs`:
```diff
@@ -60,11 +60,17 @@ function bartack(so, props) {
   }
   so = { ...defaults, ...so }
 
-  const { Path, paths } = props
+  const { Path, paths, scale } = props
 
   // Handle negative angle
   if (so.angle < 0) so.angle = 360 + (so.angle % -360)
 
+  // Handle scale
+  if (scale) {
+    so.width *= scale
+    so.length *= scale
+  }
+
   let guide = false
 
   if (so.anchor)
```

**Comment by eriese** [comment]
Late to the party on this, but I think we might want to consider having snippets that are physical elements, like buttons and bartacks, scale via an argument passed to the snippet constructor. Non-physical elements could accept that argument too but if there isn't one it'll default to scale, maybe?

I get that scale should maybe control the size of the logo and scalebox, but I don't think the size of a buttonhole should be controlled by the same setting that controls how big the text is because I don't want to have to fiddle with the slider to get an appropriate button size and then end up with a ridiculous text size. I think it should be the responsibility of the pattern designer to make reasonable decisions about how to determine button/snap/bartack sizes based on the measurements. The button size should coordinate with the placket width, for instance. 

Not sure where I think notches fall on the physical elements to markup elements spectrum, though

**Comment by woutervdub** [comment]
Currently, the annotations don't react to the `scale` option. This bugfix is to correct that. If we don't, any doll-sized pattern will have huge annotations that make it hard or impossible to even see the pattern itself.

I'm not against adding the `scale` option/parameter to some of the annotation snippets too.

**Comment by eriese** [comment]
It's true that it's a much bigger undertaking to go into all our existing patterns and add snippet scaling everywhere than to have the snippets obey the pattern scale setting, so I can see the utility of this as a stopgap measure
