### ISSUE TITLE
create-freesewing-pattern check and warn for write permissions on /usr/lib/node_modules

### ISSUE THREAD

**Issue by CatherineH** [freesewing/freesewing#364]
If the user does not have write permissions on /usr/lib/node_modules, the command

```
npm init freesewing-pattern 
```

Will stall on

```
✖ Running npm install and npm link
```

```
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path /home/chollowa/babu
npm ERR! dest /usr/lib/node_modules/babu
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '/home/chollowa/babu' -> '/usr/lib/node_modules/babu'
npm ERR!  { [Error: EACCES: permission denied, symlink '/home/chollowa/babu' -> '/usr/lib/node_modules/babu']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, symlink \'/home/chollowa/babu\' -> \'/usr/lib/node_modules/babu\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '/home/chollowa/babu',
npm ERR!   dest: '/usr/lib/node_modules/babu' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

The create-library script should check to see whether the user has write permissions.

**Comment by joostdecock** [comment]
I feel like this is out of scope. There's more than a million packages on NPM, I don't think each and every one of them should check the OS permissions prior to install, that's the package manager's job.

And as it turns out, it already does that and shows this helpful error message:
```
If you believe this might be a permissions issue, please double-check the
permissions of the file and its containing directories, or try running
the command again as root/Administrator.
```

So I don't think it's our job to do this, but I also think it would be a bad idea to catch this ourselves.
That's because any user who copy-pastes this error into google will find lots of helpful advice on how to tackle this issue. If we were to provide our own error message (which is all we can do for we can't solve the problem itself), it would be much harder for the novice user to figure out what's going on.

So I'm closing this.
