### ISSUE TITLE
Add zoom and point size slider to the designer environment

### ISSUE THREAD

**Issue by AlfaLyr** [freesewing/freesewing#368]
Some times the zoom level and the point size in the designer environment can be a bit unconvenient, so I propose:

-Add a slider in the designer mode to control the width of the svg container, instead of letting it have the width of the html element containing it.

-Making the dimension of the points in the designer mode relative to the svg container, or add a slider to change their size.

**Comment by joostdecock** [comment]
Rather than re-invent the wheel, I've submitted a pull request to [react-svg-pan-zoom](https://github.com/chrvadala/react-svg-pan-zoom) that adds support for our use case: https://github.com/chrvadala/react-svg-pan-zoom/pull/174

If it gets merged, I'll still have some work to do to polish the integration, but that's my preferred option.
If it doesn't get merged, I'll look into alternatives.

**Comment by joostdecock** [comment]
I got tired of waiting, so I implemented this myself. Consider it a first stab, it might need some fine-tuning. Also, I need to bundle this up in a new release before you'll be able to use it. But I have some other things on my todo list I'd like to get done before cutting a new version.
