### ISSUE TITLE
[feature]: bulge option on Ursula/Unice

### ISSUE THREAD

**Issue by raphaelsiz** [freesewing/freesewing#3695]
### What is it that you would like to see happen? 🤔

As a transmasc, there have been many parts of the FreeSewing site and catalog that have made me feel included, including the ability to adjust (or altogether get rid of) the bulge allowance on the Bruce boxer briefs. I think, if anyone knows how to add bulge allowance, adding it to the panty patterns would be a great way to be inclusive of transfems as well. I've known several who don't tuck and have had a hard time finding panties that fit them properly, so this seems like the perfect place to make clothing more accessible for them.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
@raphaelsiz thanks for suggesting this. It's a good idea, and we would like to do the right thing here.
However, we're also spread thin at the moment as we're trying to get the next major version out the door.

Since this is not a blocking factor for the upcoming v3 release, I have moved this to [our roadmap](https://github.com/freesewing/freesewing/discussions/1278), and will be closing this issue until a later time when we have time to work on new features.

So what the means in practice is that we are committed to implementing this, but can't commit to a timeline at this point.
