### ISSUE TITLE
Rainbow color assignment in compare pattern makes adjacent sizes difficult to distinguish

### ISSUE THREAD

**Issue by Lobotomik** [freesewing/freesewing#380]
When producing a new pattern using custom measurements, there is a feature to overlay the shapes obtained with the standard sizes. When this feature is selected, the outline for each size is shown in a different color.

Unfortunately, with 10 sizes, colors are not that easy to tell apart. Red from orange, the four greens, the two blues and purple.

Algorithmically selecting 11 maximally distinguisheable colors is as simple as it may seem. After some though, I think it is simplest to create the palette manually, picking the colors from one in the abundant pages discussing this.

From [StackExchange](https://graphicdesign.stackexchange.com/questions/3682/where-can-i-find-a-large-palette-set-of-contrasting-colors-for-coloring-many-d
) I lifted this, which may be helpful.
![image](https://user-images.githubusercontent.com/24698159/80196379-a34b0e00-861d-11ea-8e52-7510c36878d6.png)
Picking 10 nice colors from that palette should do.

**Comment by joostdecock** [comment]
A bit of clarification on how this ended up getting closed.

The criticism is valid, it's not super easy to tell two colors apart that are next to each other.
That's really because they were never intended to. The `sample` on a pattern, which provides this functionality, was always aimed at developers who wanted to see how a pattern behaved when one of it's imputs were modified.

Below is an example that samples one parameter that controls the sleevecap:

![Screenshot_2020-05-30 huey](https://user-images.githubusercontent.com/1708494/83329793-b63fa680-a28b-11ea-8e91-e97302744018.png)

For a use-case like this, the default way we handle this is fine. It does not really matter that you can differentiate between one shade of green and the next. What you want to see is how the pattern adapts between an upper and lower limit, and the rainbow approach is a pretty intuitive for that.

Switching to a bunch of more contrasting colors would arguably be less useful for developers, but also begs the question: how many colors? Sampling supports an arbitrary number of different iterations that can be provided at run-time. So we don't know how many colors we need.

We currently handle that by using HSL and then just dividing the Hue into as many steps as it takes, hence the rainbow.

Rather than change that mechanism, I've instead added the ability to pass in a `styles` array when you sample things. Each sample run then move through the array and apply the styles within to that path.

This way, the developers still get their rainbow, and in situations where that makes sense (such as on freesewing.org) we can pass a bunch of custom styles to theme the output.  
This also gives us more styling options that mere color, as you can see in teh example below where I've used different colors, dashes, and even a pattern:

![Screenshot_2020-05-30 huey(1)](https://user-images.githubusercontent.com/1708494/83329945-7927e400-a28c-11ea-8984-aed35bc21493.png)

These changes implement the feature in this repo. I've created this issue to start using it on the website: https://github.com/freesewing/freesewing.org/issues/713
