### ISSUE TITLE
[feature]: DraftRingSector plugin

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3865]
### What is it that you would like to see happen? 🤔

The in-development Senya design uses the same `draftRingSector()` function that is used in Sandy. [It was mentioned](https://github.com/freesewing/freesewing/pull/3762#issuecomment-1501672887) that moving the draftRingSector code from Sandy into a plugin would be a good feature to implement, allowing the code to be shared by multiple designs. 

This PR covers:
1. Creating a new plugin to implement the feature.
2. Creating the related documentation and tests for the new plugin.
3. Updating the Sandy design to use the new plugin.
4. Updating the Senya design to use the new plugin (If Senya has been added to the repository).

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The `draftRingSector()` code is in `designs/sandy/src/shared.mjs`. https://github.com/freesewing/freesewing/blob/develop/designs/sandy/src/shared.mjs

**Comment by bobgeorgethe3rd** [comment]
So I was thinking about this and there are so many theorectical uses cases for a plugin in like this that may become over complex to the work for all those variables and what might be better instead is a `utils.arcCpDistance(<raidus>, <angle in rad>)` that does the calculation `4 / 3 * so.radius * tan(so.angle in rads / 4)` and expecting the user to manually plot it rather than the macro doing it for them. There is room for both of course I'm just thinking this may be an easier alternative.
