### ISSUE TITLE
[bug]: Logos are missing on patterns exported to PDF

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3905]
### What seems to be the problem? 🤔

When using the `develop` branch lab development environment, logos are missing from patterns when the patterns are exported as PDF files.

- The logos appear correctly in the DraftDesign, ForPrinting, and ForCutting views in the lab.
- This issue isn't seen with exported SVG files; logos appear in SVGs just fine.
- The issue seems to have started sometime shortly before or on February 23, 2023, from looking at saved PDF files around that date.
- The problem isn't seen on lab.freesewing.dev which seems to be running an older version.

The pattern:
![Screenshot 2023-04-26 at 1 15 40 PM](https://user-images.githubusercontent.com/109869956/234692320-7785419a-c01f-4492-b290-58e8d5991c3d.png)

Exported SVG file, with logo as expected:
![Screenshot 2023-04-26 at 1 15 58 PM](https://user-images.githubusercontent.com/109869956/234692327-afac21bb-6631-44fc-a663-6710341e4d38.png)

Exported PDF file, with unexpected, missing logo::
![Screenshot 2023-04-26 at 1 16 13 PM](https://user-images.githubusercontent.com/109869956/234692340-0207e386-77e1-4f83-97a7-88153f6a1b05.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by eriese** [comment]
Tracked this one down to [when I switched us to a forked version of SVGtoPDFkit ](https://github.com/freesewing/freesewing/commit/3bf3e69730a02be2bb0ce66f0b5ce2092e20c87a) because the main version is unmaintained and inline css was not taking precedence over class-based css.

While I believe that in general we want to be using a library that resolves css in the correct way, this is causing the logo to hide because the logo svg `def` contains `stroke="none"`. It appears that different browsers handle the matter of styling svg `defs` differently. Looking at Firefox and Chrome, I see that Firefox applies only the inline styling and attributes, but that Chrome ignores the inline styling and attributes in favor of applying css from stylesheets. That's why in Firefox the logo is always filled, and in Chrome it's always an outline. We should decide which, if either, of these approaches we would like to see implemented in the SVGtoPDFkit library.

Alternatively we could decide we're happy for logo to always be an outline

**Comment by BenJamesBen** [comment]
This bug still exists in the current `develop` v3 localhost lab, using both Chrome and Safari desktop browsers.
