### ISSUE TITLE
[bug]: Reassess part resolution priorities.

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#4049]
### What seems to be the problem? 🤔

I would expect the inherited parts from from to be set after the top level after. Without this behaviour packs or importing parts will have a high chance of breaking as any stored value from the top level after is not past to the inherited parts.

Example of current behaviour:
![image](https://github.com/freesewing/freesewing/assets/16866285/a65b5c44-743d-4b6b-b26e-a41ff5af6d0e)

As you can see information from design.front & design.back is not passed onto the inherited sleevecap.sleevecap which requires the stored info from these 2 parts

Example of proposed behaviour:

![image](https://github.com/freesewing/freesewing/assets/16866285/6c4a3df7-c76f-4925-9165-2ee9653fba07)

This would apply all froms to come after the top level after part allow for stored values to be applied to inherited parts.

### Are you a FreeSewing patron? 😃

No

**Comment by eriese** [comment]
@joostdecock, I've discussed this with BG3 and I do think it's the right thing to do, if somewhat painful to implement. I just want to see if you have any objections before I dive in.

I'm wondering if there are any existing patterns that would break this way.

**Comment by joostdecock** [comment]
I'm afraid I don't *get* the example as outlined above. If you've been discussing things and that has made them more clear, than perhaps the issue can be updated. 

But this is not clear to me :shrug:

**Comment by eriese** [comment]
It's a draft order question. BG3 is playing with packs, and the idea is that packs will rely on stored values that come from parts that are not in the pack and are therefore not included in the pack parts' `after` configs. 

So assuming the following parts: 

- pack.baseSleeve
   -  relies on stored values from part.front
- pack.sleeve
   - from: pack.baseSleeve
- pattern.sleeve
   - from: pack.sleeve
   - after: pattern.front

The current draft order resolution returns

1. pack.baseSleeve
2. pack.sleeve
3. pattern.front
4. pattern.sleeve

The desirable draft order in this case would be

1. pattern.front
2. pack.baseSleeve
3. pack.sleeve
4. pattern.sleeve

so that the `after` from `pattern.sleeve` comes before its entire `from` chain rather than after it.

Having explained that I'm not even sure it'd be that painful to implement...

**Comment by joostdecock** [comment]
Thanks @eriese that does make sense to me. However, I would expect this to be handled at the config level:

- pack.baseSleeve
  - after part.front
- pack.sleeve
   - from: pack.baseSleeve
- pattern.sleeve
   - from: pack.sleeve
   - after: pattern.front

Am I missing something?

**Comment by eriese** [comment]
`pack.baseSleeve` can't be expected to know about `pattern.front `.

The workaround for now is in the file defining  `pattern.front` to `import
{ packSleeve } from 'sleevePack'` and then set `packSleeve.from.after =
patternFront` but I think that really breaks the "it just works" feel we'd
like for packs.

A different way to do it that could be a pack-specific pattern would be to
have the pack export a function that takes the `after` parts as an argument
and does that assignment for you.

I like the idea of that just fine, but to me it is still feeling right to
have `after`s resolve before `from`s because what if you're not importing
from a pack? What if you're using jaeger's sleeve but you want your own
front part to have a chance to modify the store values it uses? You're
still going to run into `bent.sleeve` drafting first.

We could argue that if you're changing store values you know enough about
the dependency chain to manipulate it manually so you should be fine using
this workaround, and then we document the workaround. Or we could make it
smooth

**Comment by joostdecock** [comment]
> `pack.baseSleeve` can't be expected to know about `pattern.front `

Nobody is claiming that. But that you think I did tells me I did not make myself clear. So I will include a code example below.

> The workaround for now is in the file defining  `pattern.front` to `import
{ packSleeve } from 'sleevePack'` and then set `packSleeve.from.after =
patternFront` but I think that really breaks the "it just works" feel we'd
like for packs.

Small nitpick: There are no packs. It was an idea before I started working on v3, but now every pattern is a potential pack. In other words, there is nothing *special* about packs.

As for the workaround above, implmenenting this in `font` seems odd to me. The way to implement what you want is in pattern.sleeve:

```js
import { sleeve as baseSleeve } from '@freesewing/sleeve-pack'
import { front } from './front.mjs'

export const sleeve = {
  name: 'mypattern.sleeve',
  from: {
    ...baseSleeve,
    after: [
      ...baseSleeve.after,
      front,
    ],
  },
  draft: ({ part }) => {
    // Do something clever here
    return part
  }
}    
```

This is what I meant when I wrote *I would expect this to be handled at the config level*

> A different way to do it that could be a pack-specific pattern

Stop right there. There shall be no specific treatments of *pack* patterns. All patterns shall behave the same.

> I like the idea of that just fine, but to me it is still feeling right to
have `after`s resolve before `from`s because what if you're not importing
from a pack? 

This is why I am being a PITA. There is no way to know for sure what the user actually wants, so we should not implement stuff in core based on the naive hope that we can read their minds.

Designers should configure things properly. Now I am not opposed to exposing additional helper methods to do that so that one doesn't need to know JavaScript very well to work with FreeSewing. For example, the example above could be:

```js
import { sleeve as baseSleeve } from '@freesewing/sleeve-pack'
import { front } from './front.mjs'

// Make sure sleeve gets drafted after front
sleeve.updateConfig(['after'], [...sleeve.after, front])
 
export const sleeve = {
  name: 'mypattern.sleeve',
  from: baseSleeve,
  draft: ({ part }) => {
    // Do something clever here
    return part
  }
}    
```

Perhaps even a more purpose-build `.draftAfter()` method can be added. That's something we can figure out.

But:

- Part dependencies must be configured in the pattern. No *guessing* what to do in core
- All patterns behave the same. Packs are not special

I'm happy to see proposals for methods to help people create a working config. If not, I can implement something myself.

But I still remain unconvinced that there is any _reassessment of part resolution priorities_ to be done, or that there's even a problem to begin with.

disclaimer: This is all just code from the top of my head. I hope it gets the point across.

**Comment by eriese** [comment]
You're right, all the behavior should be the same because packs are simply patterns. The code gets the point across, and I think we'd need to tweak it if we were going to document it as the freesewing-approved way to handle this problem, but it's workable.

However:

I don't feel I'm suggesting that core make *guesses* here because I'm suggesting we change the standard behavior. Right now core is already making a determination about what `after` and `from` means for the draft order. It's not a very intentional determination, it just so happens to resolve `from` dependencies recursively and then `after` dependencies recursively, and then uses the resulting "distances" as sort values for the draft order. I'm suggesting that we make a different, more intentional, and potentially more sensible determination. It will do the same thing for all patterns, and the docs will reflect what people can expect from draft order resolution. 

It's possible that the change is as simple as resolving `after` before `from`, but I don't want to promise that. A preliminary test says that swapping that order doesn't break anything that's currently published.

I'm open to the idea of some utility methods for manipulating part config, but I think that's the path that actually means putting things in core to cover special use cases

**Comment by eriese** [comment]
Yes, I believe we're on the same page now.
