### ISSUE TITLE
Feature request: A plugin to mirror points around a line

### ISSUE THREAD

**Issue by destos** [freesewing/freesewing#405]
This feature would flip points/paths across a line defined by two points similar to how the current flip plugin works but on an arbitrary axis.
Current flip plugin: 
https://github.com/freesewing/freesewing/blob/develop/packages/plugin-flip/src/index.js

Unlike the current flip plugin, it would need to take in two points to build the flip axis, and possibly be configured to flip selected points and paths. 

My use case is a section of a part in a pattern that needs mirrored/reflected across 45°. The entire part does not need to be reflected.
 
suggested macro API:
```javascript
macro("reflect", {
  start: Point,
  end: Point,
  points: [Point],
  paths: [Path]
}
```

Similarly to the current flip plugin, it would loop through all supplied paths ( or optionally, points )
and reflect them across the line defined by start/end. the new points/paths are added to the part.

Should we add an option to copy/move the existing points? My use case is to create a copy.

As references to points/paths are referenced as properties on the part, we need a way to provide new names to the points/paths if they are being added to the part's existing points/paths.

**Comment by joostdecock** [comment]
Thank you for the detailed suggestions. A few remarks after an initial read-through:

> suggested macro API

I'm a bit concerned that using `start` and `end` in the API could be a bit confusing. As in, any 2 (different) points suffice to know the mirror line. This might give the impression that the distance between `start` and `end` is relevant somehow? Would something like `mirror: [Point1, Point2]` be more intuitive?

> Should we add an option to copy/move the existing points?

Why not, although copy should probably be the default. Maybe an `move: Bool` option in the API that defaults to `false`

> we need a way to provide new names to the points/paths

The [round macro](https://freesewing.dev/reference/macros/round/) take a `prefix` option that prefixes the names of points it creates. We could do that for simple use-cases. It could even have a default so that things *just work*.

For more advanced use-cases, we could take a `nameFormat` (or a better name) API option that lets the user/developer pass in a method that takes the source point/path name as input, and returns the new name. That way, we can let them control how points are named. 

Added this to the 2.7 milestone.
