### ISSUE TITLE
Instagram post charlie + wahid

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#4141]
### Where can we find the awesomeness? 🤔

https://www.instagram.com/p/Crp-CHjMm1q/comments/

### Do you know what FreeSewing design was used? 🧐

Charlie, Wahid

### Do we have permission to (re)post this? ✅

None

**Comment by tangerineshark** [comment]
Sent an insta DM to see whether it would be cool to post this as a Showcase - stay tuned!

**Comment by tangerineshark** [comment]
They're on board! Will assign myself and post this shortly!

**Comment by tangerineshark** [comment]
Okay I finally actually got around to doing this (and only accidentally unliked and re-liked this poor stranger's Insta post once in the process)! It's in the Showcaseposts on Strapi now.

Pondering whether I should save a tiny explanation on how to snag pics from Instagram in their original format rather than a shitty screengrab (you go to Inspect, and then open up the little div class, and then there's a URL in there you can grab to open a save-able version). In the meantime, I'll just keep accidentally double-clicking strangers' posts while I try to remember. 😅
