### ISSUE TITLE
(i18n) Designs do not inherit translations

### ISSUE THREAD

**Issue by eriese** [freesewing/freesewing#4158]
### What seems to be the problem? 🤔

Not really a bug, but also not exactly a candidate for going into the site-specific issues: 

Short of manually duplicating keys, we currently don't have a way to get the options translations from inherited designs associated with the inheriting designs. I'm imagining that having those translations available is v3-critical, so I'm marking it as such.

So far I don't have any particularly smart ideas about how to accomplish it, but what I can think of to offer some place to jump off of is:
- as part of i18n's build step, it checks design dependencies and merges inherited translations into the namespaces of inheriting designs. I think this will slow down the builds, but it's a one and done solution so I think it's better than my other idea
- designs export their namespaces, same way that components are now doing. I don't like this one because it relies on pattern designers to take that extra step and will mean we have to go in and change all existing designs

### Design / Plugin / Package 🧐

packages/i18n

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by eriese** [comment]
@freesewing/developers Anyone have any ideas on this? I'm happy to implement it once we come up with something

**Comment by eriese** [comment]
@joostdecock I have now found `i18n/shared-options.yml` and the `locales/[loc]/options/index.js` that makes use of it. It looks like the build step doesn't use it anymore, though, and I assume the index file is not currently getting generated by anything. Do you have thoughts on whether it's a preferable system to the ones suggested above? 

An argument in its favor is that shared options can stay in the not-necessarily-intuitive files they're in now. 
An argument against it is that it's gotta be maintained manually, and maybe some of those shared option translations should go in a more intuitive place

**Comment by joostdecock** [comment]
While I haven't gotten around to any sort of implementation for it, my opinionated take on the matter is that translations for designs should ship with the design. Which would allow designs to *extend* them.

The shared options file with the prebuild step is a v2 hack, a slog to maintain, and it leads to vague and generic translations for options and they're supposed to work for various designs implementing this option.

Keeping the options next to the pattern code should make more sense. It allows us (and others) to import them along with the pattern, and so on.

I foresee that in v3 we will no longer publish an i18n package because patterns will carry their own translations, and everything else (websites, emails, ...) is our own internal stuff for which we've already have a rather flexible solution right now where we keep thee translation files next to the components.

My main reason for holding off on implementing this translations-next-to-patterns change is that we've been having some issues with crowdin lately and there's even been talk of moving to a different platform.
So I'd like those questions to resolve first to ensure that whatever we implements can work with the translation software.

It's perhaps something we can add to the call agenda, as I hope to have answers for the crowdin issues at that time.

**Comment by joostdecock** [comment]
#4255 is merged. Closing.
