### ISSUE TITLE
New Bella body block for Tricia: Something Went Wrong

### ISSUE THREAD

**Issue by triciamonster** [freesewing/freesewing#4216]
Hi, getting this error in trying to generate the Bella pattern. I am well outside the largest plus size, maybe that is the issue?
User ID: Tdiaz

<img width="941" alt="Screenshot 2023-06-02 at 7 51 45 PM" src="https://github.com/freesewing/freesewing/assets/11509618/1c57efc4-debc-4cbd-b2a4-a54afc1aedbf">
<img width="710" alt="Screenshot 2023-06-02 at 7 53 23 PM" src="https://github.com/freesewing/freesewing/assets/11509618/96972fe3-3767-48d2-9643-1039c9861214">

**Comment by joostdecock** [comment]
Dear @triciamonster thanks for taking the time to report this.

I don't know if you're familiar with this FAQ but it's relevant: https://freesewing.org/docs/faq/womenswear-blocks/

While it's possible that there's a problem that's due to measurements being taken incorrectly (I'd have to see the measurements to check) it is also possible that it just doesn't work in its current incarnation 🤷

If you save the pattern to your profile and share the link here we could have a closer look.

**Comment by BenJamesBen** [comment]
The issue occurs because there is an error in the Bella design in situations when the bustline is close to or below the waistline. I believe that the issue has already been fixed in the upcoming v3 version of FreeSewing, via PR #4001, but the fix is not currently available on the existing website.

As a workaround, you could change your HPS To Bust measurement to 16.75 inches. This will allow Bella to be able to draft a pattern without error. However, if you use this workaround, please be aware that manual fitting and alteration of the back (and possibly the front) pattern pieces are likely to be needed. Please make a test garment, check fit, and make alterations as necessary before trying to make the final garment.

**Comment by joostdecock** [comment]
Closing as it's fixed in v3, a workaround is provided, and there's no feedback from the user.
