### ISSUE TITLE
[bug]: Exported JSON or YAML from Hugo pattern shows mismatched version number

### ISSUE THREAD

**Issue by evilrobotfromouterspace** [freesewing/freesewing#4878]
### What seems to be the problem? 🤔

Steps to reproduce
1. Create a hugo in the main freesewing.org application
2. View the pattern in paperless mode and observe the version number shown (v2.22.2 at time of writing)
3. Export the pattern JSON or YAML
4. Expected: data.json and data.yaml shows "version": "2.22.2"
4. Observed: data.json and data.yaml shows "version": "2.16.1"

Not sure whether this is really a bug or it matters for anything, but since I noticed the inconsistency I thought I should report it.

### Design / Plugin / Package 🧐

designs/hugo

### Are you a FreeSewing patron? 😃

Yes, I am a tier-4 patron ❤️  💙

### Additional context

![Screenshot 2023-09-01 at 8 02 36 AM](https://github.com/freesewing/freesewing/assets/143673955/e45883f2-0c1c-4cdf-b9d2-ef81643b1f44)
![Screenshot 2023-09-01 at 8 01 52 AM](https://github.com/freesewing/freesewing/assets/143673955/3b2f1820-fbd6-4e0b-9a57-289aaaa1a472)

**Comment by joostdecock** [comment]
Huh, nice catch.
I don't know if you're aware but we're working on the next major version of FreeSewing (v3) for which you can see the progress in #4071 

As such, I'm not going to fix this because the impact is minimal and we'd like to move to version 3 as soon as possible.

That being said, I appreciate that you took the time to report this. I'm sure v3 will have plenty of bugs for you to report too ;)
