### ISSUE TITLE
[bug]: clicking the "github gist" export button doesn't work and leads to a 500 error

### ISSUE THREAD

**Issue by gregsadetsky** [freesewing/freesewing#5056]
### What seems to be the problem? 🤔

repro steps:
- go to https://freesewing.org/create/aaron/for/size-36-b/
- click "export pattern" in the left sidebar
- click the "github gist" button in the main page content

result: nothing happens in the UI & the server actually returned a 500 error:

<img width="589" alt="image" src="https://github.com/freesewing/freesewing/assets/1017304/496e9feb-f0fd-4f35-a160-93e59eebd245">

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Thanks for reporting this @gregsadetsky 
We froze the v2 branch ... checks notes ... about a year ago 😂 and at the end of last month release v3.0.0.
We're now getting ready to migrate FreeSewing.org to version 3, where this problem with no longer be an issue or even relevant because we keep all state in the URL. So to share a pattern, you merely have to copy the URL.

I'm not going to write a v2 fix for this. I hope that by the end of this month, freesewing.org will run on v3 code and this this will no longer be an issue.

**Comment by gregsadetsky** [comment]
Ah got it, thank you! Since I saw v3 had been released, I thought that the site was running the latest version

Makes sense to not touch it if it's going to be deprecated.

Thank you!
