### ISSUE TITLE
[docs]: Missing designer notes for various designs

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#5364]
### Designs without designer notes 

Here's a list of designs that do not have any designer notes:

- Designs by @woutervdub 
  - [x] albert
  - [x] benjamin
  - [x] cornelius
  - [x] gozer
  - [x] hi
  - [x] hortensia (with @stoffsuchti )
  - [x] noble
  - [x] octoplushy
  - [x] otis
  - [x] penelope
  - [x] skully
  - [x] waralee
- Designs by @bobgeorgethe3rd 
  - [x] bee
- Designs by @AlfaLyr 
  - [x] diana
  - [x] holmes
  - [x] sandy
- Designs by @QuentinFelix 
  - [x] florent
- Designs by @SeaZeeZee 
  - [x] lucy
- Designs by @starfetch 
  - [x] lunetius
  - [x] tiberius
  - [x] wlburga
- Designs by @Thrunic 
  - [x] onyx
  - [x] shelly
- Designs by @hellgy / @biou 
  - [x] yuri

### Notes

I am aware that for some of the people I've at-mentioned, this might come a bit out of the blue as their designs have been around for a while, and they are not involved with FreeSewing on a daily basis.

For those people: We are gearing up to migrate FreeSewing.org to version 3 of FreeFewing. 
We have a new feature called 'designer notes' where people can talk a bit about the design, why they made it, how they made it, whatever. [Here's an example](https://next.freesewing.org/docs/designs/aaron/notes).

All of the work of porting your designs to v3 and getting them ready for the relaunch has already been taken care of.
But the one thing I cannot do on your behalf is put words in your mouth.
So, if you could write a few words about the design you made, I would very much appreciate it.

You can just comment on this issue, and I'll make sure it goes in the right place.
Thanks for doing this soon because I'd like to relaunch towards the end of this week, and we still need to allow time for translation.

joost

**Comment by QuentinFelix** [comment]
Hi all, long time no see. I hope everyone is all right and I am glad to see this project is still going strong. On my end I have not had a lot of time to sew personal projects. I became tutor at the tailoring academy in Macclesfield (UK) and also got married and have a 3 months old daughter. So I'll just drop a few lines straight away so that I don't forget about this project.

About the Florent flat cap:
I found a scan of a hand drawn flat cap pattern, for one size and experimented with scaling on the screen of my laptop and tracing it through with tracing paper stuck on the screen. The goal was to make it fit my (rather big) head circumference. I also made a few caps, improving the shapes with each prototypes. But then someone asked me to make one for them... meaning I would need to scale my parts to fit their head circumference. At that time I heard about freesewing and as I am a bit of a geek I gave it a try to draw my (then improved) pattern pieces. Sure enough I was able to play with it and get it to scale the parts, to fit any head circumference. I believe since then a few improvements have been added by other members of the community and it is always a pleasure to see theses caps popping up on the freesewing website or on Instagram.

**Comment by AlfaLyr** [comment]
Glad to write some notes.

About Diana draped top:
This project started because one day I wanted to sew a sleeveless draped top with some leftover fabric I had after making another dress. I used a basic body block from Freesewing, and manually modified the pattern to create a draped neckline. Since I was pretty happy with the result, and the modifications were simple, I decided to create a Freesewing pattern for it, so it could be available for other people.
The original top I made had two layers, a nice viscose with a beautiful flower pattern that acted as a lining, and a sheer chiffon on top that let the viscose show through. The nice thing about adding a lining is that you can see it in the drape, which gives a beautiful effect!
No interesting story about the name, just the first name that came to my mind that started with the letter D of draped :)

About Holmes hat:
The idea of Holmes hat came from a youtube video I was watching once ([here](https://www.youtube.com/watch?v=H24VBFMZJF4)), in which Bernadette Banner is making a Sherlock Holmes deerstalker hat, and struggles to find the right shape of the gores to form the dome shape, which ends up doing by trial and error. As a physicist, I can justify solving a problem with an iterative process when there's an analytical solution, so I just calculated the shape needed, and implemented it in a Freesewing pattern, creating a plugin to calculate gore shapes.
The name was an easy choice, I just needed a name starting with H for a Sherlock Holmes hat :)

About Sandy circle skirt:
Sandy was my first pattern after I made the bib tutorial. Usually, no one needs a pattern to make a circle skirt, you just fold your fabric, run your numbers and cut the circle. However, I wanted an automated way to get those numbers and that was not limited to a full or half circle, so I decided to make the pattern. Additionally, I gave it the option to have an accurately curved waistband, which I use also for other projects.
The name is a tribute to Sandy, Olivia Newton John's character in Grease, who wears a fair amount of circle skirts as a typical 50s teenager.

**Comment by Thrunic** [comment]
I've made PRs #5370 for Shelly, and #5371 for Onyx, that provide the designer's notes, as well as some other documentation additions/fixes that I noticed while writing the notes.

**Comment by SeaZeeZee** [comment]
Ive opened a PR to add my designer notes for Lucy.

**Comment by bobgeorgethe3rd** [comment]
Opened a PR with designer notes for Bee

**Comment by hellgy** [comment]
I tried to write something about the Yuri pattern, I hope it helps. Feel free to improve/correct it if necessary.

> The idea behind Yuri was to get a hybrid cardigan/sweatshirt that could be easily opened and closed, and sewn without the hassle of zips. When I started sewing, one of the things I hated the most was sewing zips (but now it's ok, yay!).
> 
> I wanted a big shape that would be comfortable to wear while cycling or knitting on the couch, plus size or not, with or without breasts :)
> 
> This pattern was made in collaboration with @biou , my husband, who's also a programmer. We had a lot of fun creating and testing the pattern together and we were happy to be able to contribute a little to freewrestling :)
> 
> We used a mix of the two Huey & Hugo hoodies and reshaped them a bit to change the front/opening and length, and BAM, Yuri was born!
> 
> I recommend using a soft sweatshirt fabric, you can add a lining but it's not essential. It can be nice in red for a little red hood costume, or a nice gift for a pregnant person :)

**Comment by anna-puk** [comment]
> About Holmes hat: The idea of Holmes hat came from a youtube video I was watching once ([here](https://www.youtube.com/watch?v=H24VBFMZJF4)), in which Bernadette Banner is making a Sherlock Holmes deerstalker hat, and struggles to find the right shape of the gores to form the dome shape, which ends up doing by trial and error. As a physicist, I can justify solving a problem with an iterative process when there's an analytical solution, so I just calculated the shape needed, and implemented it in a Freesewing pattern, creating a plugin to calculate gore shapes. The name was an easy choice, I just needed a name starting with H for a Sherlock Holmes hat :)

As a fellow physicist, I'm with you in preferring analytical solutions. I think there may be a typo in your description: did you perhaps mean to say "I cannot justify"?

**Comment by AlfaLyr** [comment]
> @AlfaLyr
> 
> > About Holmes hat: The idea of Holmes hat came from a youtube video I was watching once ([here](https://www.youtube.com/watch?v=H24VBFMZJF4)), in which Bernadette Banner is making a Sherlock Holmes deerstalker hat, and struggles to find the right shape of the gores to form the dome shape, which ends up doing by trial and error. As a physicist, I can justify solving a problem with an iterative process when there's an analytical solution, so I just calculated the shape needed, and implemented it in a Freesewing pattern, creating a plugin to calculate gore shapes. The name was an easy choice, I just needed a name starting with H for a Sherlock Holmes hat :)
> 
> As a fellow physicist, I'm with you in preferring analytical solutions. I think there may be a typo in your description: did you perhaps mean to say "I cannot justify"?

Oh, of course, thanks for catching the typo! :)

**Comment by starfetch** [comment]
Created PR #5387 for my patterns :)
Also, third physicist here in this thread!

**Comment by joostdecock** [comment]
Thanks everyone 🙏
