### ISSUE TITLE
[bug]: Certain design options not visible in design docs

### ISSUE THREAD

**Issue by ArcticCoder** [freesewing/freesewing#5522]
### What seems to be the problem? 🤔

Using Otis as an example, [the documentation page](https://freesewing.org/docs/designs/otis) (and some other places) show a standard list of the design options, but two entries are blank. This applies to many other designs as well, and trying to look through the source as a newbie I couldn't find a simple commonality between the missing options.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

If there is "grunt work" or simple code fixes to do on this, I would be happy to give it a shot! I have the dev environment setup, and I'm a 3rd year computer science student, though I don't have experience with the specific technologies freesewing uses.

Many, but not all, are related to the sleeve cap options.

Full list of designs where I saw problems:
- Breanna (Sleeve cap)
- Brian (Sleeve cap)
- Charlie
- Diana (Sleeve cap)
- Huey (Sleeve cap)
- Onyx
- Otis
- Simon(e) (Sleeve cap + A bunch of others)
- Sven (Sleeve cap)
- Teagan (Sleeve cap)
- Tiberius
- Yuri (Sleeve cap)

**Comment by joostdecock** [comment]
Thank you for reporting this. Since you offered to help, l will explain what's going on, and if you want you can fix it :wink: 

There's actually two things happening here. Let's start with the common aspects:

The *index* page of a design looks like this (using otis as an example):

```
---
title: "Otis: the simple baby romper"
---

<DesignInfo design='otis' docs />
```

We use [MDX](https://mdxjs.com/) which allows us to use Markdown + custom components.
This `DesignInfo` tag is such a custom component.

Which components can be used in MDX is defined in [this file](https://github.com/freesewing/freesewing/blob/4de6a4fbf83c9816ae343a9a630e3c2e7f3a5bc4/sites/shared/components/mdx/index.mjs).

There you'll see that `DesignInfo` is imported from `shared/components/designs/info.mjs`.

This is where there's two different bug, so let's tackle them one by one:

## Typo when calling OptionGroup recursively

On line 52 of `shared/components/designs/info.mjs` there's a typo:
```js
          <OptionGroup id={sid} key={sid} t={t} group={entry} desing={design} />
```

Did you spot it? It passes down `desing` instead of `design`. 
This line calls OptionGroup recursively. But it does it does not pass down `design` (instead passing down `desing`) so when a group exists in a group (which is when this is called recursively) it will not know which design the option belongs to, and thus we won't be able to resolve the title.

This is why sleevecap is broken everywhere (because sleevecap is a group under the advanced group) and why there's so much broken in simon(e) since it's a pattern with various nested groups.

To fix this, just fix the typo :)

## Case mismatch in folder name

If you follow the component trail you'll see that the actual display of the link to the option is handled by `DocsTitle` in `shared/components/mdx/docs-helpers.mjs`.

This will load the title from the pre-built navigation object, which is constructed from the content on disk.

However, URLs must always be lowercase, so it will look for `sleevetype` (for example).
The reason it doesn't work is that the folder that should be `sleevetype` is named `sleeveType` which is the real problem.

To fix this, rename all folders so they are lowercase.

Good luck, and let me know if you have any questions.
