### ISSUE TITLE
[bug]: must save before making changes and saving

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#5534]
### What seems to be the problem? 🤔

When going in to edit an existing pattern, I have to save once before making changes or it will revert. This only applies to editing existing patterns I've saved and closed, and specifically overwriting the existing save. It's happening on every pattern I've edited after saving and closing the first time, and it happens every time I open it to make changes.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
This is a tricky problem. The reset is caused by updating the loading context, which somehow impacts the local state.

This problem will not occur when the page is cold-loaded (SSR + hydration), which will initialize the state. So it's a rather subtle issue with state across page transitions.

I tried passing in the context updater rather than loading it, but that did not resolve the matter.
Furthermore, the fact that the second save will just work as expected has me somewhat stumped.

To side-step the problem until I have more time to get to the bottom of it, the edit view will now silently save the pattern in the background, but only on the first load, which means the pattern will not have changed.

By silently, I mean that we won't update the loading context, and this does resolve the matter as now the first save from the user perspective is actually the second save.
