### ISSUE TITLE
Port @Sewanista's skirt draft to freesewing

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#573]
This is a todo from #570 

@Sewanista has a skirt draft that she's made in valentina/seamly, and it's already a parametric design. She's looking for someone to help her code it. @enyachoke offered to help her with that, so the idea is that the two of them can work on this together.

**Comment by joostdecock** [comment]
I'm available for any help you need on this :slightly_smiling_face:

**Comment by stoffsuchti** [comment]
I am curious to see the pattern or pictures / linedrawings

**Comment by Sewanista** [comment]
Ive posted a link to my dropbox in the discord, but to save you hunting around I'll post it here as well. 
https://www.dropbox.com/sh/0ggk15j0c3h4yhd/AAAZDBI6fABpVOSsvtJsYOaBa?dl=0
Its a very simple straight skirt draft where I have converted the dart allowances to proportions rather than absolute values. It drafts up quite well over a wide range of sizes, with the caveat that it doesn't take into account non standard weight distribution such as full stomach/flat seat or vice versa. It was done as a proof of concept. It is also missing some curves - I drafted the waistline straight rather than curved. It won't make much difference in practice for a hobby sewer, but its not particularly elegant. 
Straight skirts are fairly easy to draft as they are simply a tube that tapers at the upper edge. Complex patterns such as bodices and sleeves are going to take a bit more time.

**Comment by Sewanista** [comment]
the file I've linked to includes the Seamly pattern, a selection of varying measurement set files and a pdf of the drafting method written out for drafting on paper.

**Comment by enyachoke** [comment]
Thanks @Sewanista  am starting to lay down the today I will update you on this issue on the progress and any questions I could have.

**Comment by joostdecock** [comment]
Stale. Closing
