### ISSUE TITLE
Privacy Friendlyness of FreeSewing

### ISSUE THREAD

**Issue by stoffsuchti** [freesewing/freesewing#578]
I am very worries in witch direction FreeSewing is evolving in a perspective of privacy. The use of discord and zoom ist excluding me nearly total from the daily business of FreeSewing. Why where BigBlueButton and Mumble nit considered? Why are the chats not based on Matrix/Riot/Elements? 

It afraids me and I am very sad about this evolution.

**Comment by stoffsuchti** [comment]
FreeSewing has no presence on i.e. Mastodon (open and federated Twitter alternative). That is sad to.

**Comment by joostdecock** [comment]
First of all, our [privacy notice](https://freesewing.org/docs/about/privacy/) hasn't changed in over 2 years.
So saying that FreeSewing's privacy friendliness is changing is not correct.

Your gripe is with the people who volunteer their time to work on FreeSewing. 
You're unhappy because they don't seem to care as much about privacy as you do. Or at least they make choices that are more pragmatic and less principled.

I can understand that that saddens you, but working with volunteer contributors all over the world requires compromise and consensus. The consensus now is that using Zoom + Discord is a boon for the project.  

Since we moved to Discord, and started having Zoom calls, the contributions and cooperation have increased significantly.
It's early days, but it really feels like a great success
Other alternatives have been considered, but they were too cumbersome or created too much friction. I take full responsibility for that choice.

> FreeSewing has no presence on i.e. Mastodon (open and federated Twitter alternative). That is sad to.

Your happiness should not depend on where FreeSewing sets up camp.
I can't make you happy. We can't make you happy. Happiness must come from within.

I hope you find it.
