### ISSUE TITLE
[feature]: Show designer notes for all levels of the user experience

### ISSUE THREAD

**Issue by woutervdub** [freesewing/freesewing#5848]
### What is it that you would like to see happen? 🤔

Designer notes is a good way to communicate with the user about the design, specifically for dimensions that are not easily calculated in the `options` part of the interface. Currently, the default user experience does not show these designer notes, making the feature less useful.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by woutervdub** [comment]
Hmmm, maybe it's just a `lab` issue then?

**Comment by BenJamesBen** [comment]
Using the up-to-date `develop` branch and testing the Bob design, I am still not seeing the issue in the localhost lab. "Messages from the designer" show up at all user experience levels.

When you see the issue, which user experience levels are missing the designer notes? And, what design are you looking at?

**Comment by woutervdub** [comment]
I noticed it when I was working on `tristan`, in that branch. And I've tried to keep that branch up-to-date with `develop`. When you choose the Peplum option, the size/width of the peplum is communicated through that system

**Comment by BenJamesBen** [comment]
I was able to see the behavior using your `tristan` branch, with the Bob design. User experience levels 1 and 2 were missing designer notes, while levels 3, 4, and 5 showed them properly.

However, I suspect that the `tristan` branch is old. Specifically, I noticed that bug #5653 is still present in it, and that bug was fixed on Dec. 30, 2023.

**Comment by BenJamesBen** [comment]
Closing as Already Fixed in `develop`.
