### ISSUE TITLE
[bug]: Jager sleeves still have problems, though ease is fixed.

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#6023]
### What seems to be the problem? 🤔

Jager (and Bent) sleeves generate larger for smaller bicep measures, and smaller for larger bicep measures.
All else equal, at default ease of 15% Jager, with 20cm set for bicep circumference results in this sleeve
![image](https://github.com/freesewing/freesewing/assets/84648053/f183bff7-2942-40bd-87af-5abd32d43f56)
with the bicep measure set to 30cm this is the sleeve that is generated 
![image](https://github.com/freesewing/freesewing/assets/84648053/2b181841-d7dc-453e-a901-077fe4f2b4f1)
and with a bicep of 40 cm this is the sleeve that is generated 
![image](https://github.com/freesewing/freesewing/assets/84648053/619318da-9229-44ae-b2ac-c1d0741ff180)
Moving the bicep ease slider now correctly makes it larger for more ease, and smaller for less ease however.

### Design / Plugin / Package 🧐

designs/jaeger

### Additional context

I checked and Bent has the same issue.

**Comment by BenJamesBen** [comment]
The problem is that:
1. Bent's sleeve width is inversely proportional to the sleevecap height.
2. Bent's sleevecap height is proportional to the biceps circumference.
3. So, as the biceps get larger, the sleevecap gets taller and the sleeve gets narrower.

A possible solution might be for Bent to start with a baseline sleevecap height simply based on the armhole size, then decrease  sleevecap height based on biceps circumference. So, a larger biceps circumference would result in a shorter sleevecap and a wider sleeve.

_These values are entirely made up and probably bogus_, but for example:
```diff
--- a/designs/bent/src/sleeve.mjs
+++ b/designs/bent/src/sleeve.mjs
@@ -1,7 +1,7 @@
 import { front } from '@freesewing/brian'
 
-function draftBentSleeve({ Path, paths, points, store, options, part }) {
-  function draftSleeve(part, tweak) {
+function draftBentSleeve({ Path, paths, points, store, options, part, log }) {
+  function draftSleeve(part, tweak, target) {
     let { Point, Path, points, store, options, measurements, utils } = part.shorthand()
     // Sleeve frame
     points.top = new Point(0, 0)
@@ -13,9 +13,12 @@ function draftBentSleeve({ Path, paths, points, store, options, part }) {
     )
     points.boxBottomRight = points.boxBottom.shift(0, points.boxTopRight.x)
     points.boxBottomLeft = points.boxBottomRight.flipX()
+    const bicepsConstant = 0.15
+    const baseSleeveHeight = target * options.sleevecapHeight
+    const bicepsFactor = measurements.biceps * (1 + options.bicepsEase) * bicepsConstant
     points.armCenter = points.top.shift(
       -90,
-      measurements.biceps * (1 + options.bicepsEase) * options.sleevecapHeight * tweak
+      (baseSleeveHeight - bicepsFactor * tweak)
     )
     points.armRight = points.armCenter.shift(0, points.boxTopRight.x)
     points.armLeft = points.armRight.flipX()
@@ -133,7 +136,7 @@ function draftBentSleeve({ Path, paths, points, store, options, part }) {
   let tweak = 1
   let target = store.get('sleevecapTarget')
   do {
-    draftSleeve(part, tweak)
+    draftSleeve(part, tweak, target)
     runs++
     delta = store.get('sleevecapLength') - target
     if (delta > 0) tweak = tweak * 0.99
```

**Comment by joostdecock** [comment]
@all-contributors please add @RockerKitten for question

**Comment by BenJamesBen** [comment]
A better fix might be to base the width of the sleeve directly on the biceps measurement. (Currently the width is hardcoded as a fraction of the sleeve opening, regardless of the biceps measurement.)

```diff
-- a/designs/bent/src/sleeve.mjs
+++ b/designs/bent/src/sleeve.mjs
@@ -5,7 +5,8 @@ function draftBentSleeve({ Path, paths, points, store, options, part }) {
     let { Point, Path, points, store, options, measurements, utils } = part.shorthand()
     // Sleeve frame
     points.top = new Point(0, 0)
-    points.boxTopRight = points.top.shift(0, (store.get('sleevecapTarget') / 5.8) * tweak)
+    const easedQuarterBiceps = (measurements.biceps / 4) * (1 + options.bicepsEase)
+    points.boxTopRight = points.top.shift(0, easedQuarterBiceps * tweak)
     points.boxTopLeft = points.boxTopRight.flipX()
     points.boxBottom = points.top.shift(
       -90,
```

Comparing before/after patterns using curated measurements sets, it seems that this new formula produces roughly the same patterns as before. However, as biceps circumference increases, the sleeve width now increases instead of decreasing.

![Screenshot 2024-09-20 at 7 15 41 AM](https://github.com/user-attachments/assets/6b2bbd0e-7d95-41e7-b5a4-3f289c44ac52)
![Screenshot 2024-09-20 at 7 16 00 AM](https://github.com/user-attachments/assets/0c9d693d-72be-4f64-8da4-112da4915a40)

![Screenshot 2024-09-20 at 7 18 47 AM](https://github.com/user-attachments/assets/c9aaf1e9-64b9-4c49-99f4-1d0f8573a71a)
![Screenshot 2024-09-20 at 7 18 10 AM](https://github.com/user-attachments/assets/3e9bcc64-3949-40d8-8f7f-bdf58075d437)

![Screenshot 2024-09-20 at 7 15 18 AM](https://github.com/user-attachments/assets/f690f706-e5b1-4a78-949f-caf7c34d4ec7)
![Screenshot 2024-09-20 at 7 15 02 AM](https://github.com/user-attachments/assets/edcc5419-7144-4a76-8f55-8a9d2617e1e4)

![Screenshot 2024-09-20 at 7 19 24 AM](https://github.com/user-attachments/assets/4d017f62-b718-407e-aee7-ec0686eb21c8)
![Screenshot 2024-09-20 at 7 20 06 AM](https://github.com/user-attachments/assets/f722d19b-9cf9-4b31-bf5b-6f34f0efc212)
