### ISSUE TITLE
[bug]: test pattern view on hugo/teagan/brian does not show impact of draft for high bust

### ISSUE THREAD

**Issue by anna-puk** [freesewing/freesewing#6068]
### What seems to be the problem? 🤔

When I use the 'test pattern' view on `hugo` to check the impact of the 'draft for high bust' design option, nothing changes, even though it _does_ affect the actual pattern (for measurement sets that have a separate high bust measurement).

I see the same thing for `teagan`, so I think `brian` and all its descendants are probably affected. I've tentatively marked this as a brian bug.

### Design / Plugin / Package 🧐

designs/hugo

### Additional context

This can be reproduced using the left-most curated measurements set, e.g. like this: https://freesewing.org/new/hugo#view=%22test%22&settings=%7B%22measurements%22%3A%7B%22biceps%22%3A295%2C%22chest%22%3A830%2C%22hpsToBust%22%3A230%2C%22hpsToWaistBack%22%3A360%2C%22neck%22%3A360%2C%22shoulderToShoulder%22%3A360%2C%22shoulderSlope%22%3A20%2C%22waistToArmpit%22%3A190%2C%22waistToHips%22%3A90%2C%22hips%22%3A880%2C%22shoulderToWrist%22%3A420%2C%22wrist%22%3A150%2C%22head%22%3A510%2C%22highBust%22%3A820%7D%2C%22units%22%3A%22metric%22%2C%22only%22%3A%5B%22hugo.back%22%5D%2C%22paperless%22%3Atrue%2C%22options%22%3A%7B%7D%2C%22sample%22%3A%7B%22type%22%3A%22option%22%2C%22option%22%3A%22draftForHighBust%22%7D%7D

**Comment by BenJamesBen** [comment]
(#5975 is not related. It was a bug where test view was crashing with some designs.)

I believe that the cause of this bug is that the conditional `plugin-bust` is not getting loaded. 
- I think that the patterns are loading plugins first, before the sampling process generates the various sets of settings.
- During the plugin-load phase, the initial settings have blank options, `options: {}`, so `plugin-bust`'s condition isn't met and the plugin doesn't get loaded.
- Afterwards the sampling process generates settings with `options: { draftForHighBust: true }`, but it is too late because the core infrastructure already decided to not load `plugin-bust`.

**Comment by joostdecock** [comment]
This might be tricky to resolve, and is rather niche. So I consider this low priority.

It's a side effect of the fact that we sample different sets in a single pattern. But a conditional plugin is loaded in the pattern yes or no. So it's either always there, or never there.

You can verify this by toggling the `draftForHighBust` option in the draft view, and then move to the sample/test view.
In both cases, the sample will not show any difference. But if you compare both versions, you will notice that they are different. Once with the high bust used instead of chest, and once not.

So the plugin is used (or not used) for all sampled measurement sets.

I guess the proper solution here is to consider changing the way conditional plugins are loaded.

**Comment by BenJamesBen** [comment]
(This possible fix changes the character of `plugin-bust` where instead of having it be a conditionally-loaded plugin, it becomes a regular plugin that is always loaded. The condition check is moved into the `preDraft` hook code. I'm not sure whether changing the character of `plugin-bust` is something we would want to do.)

```diff
+++ b/plugins/plugin-bust/src/index.mjs
@@ -4,14 +4,19 @@ export const plugin = {
   name,
   version,
   hooks: {
-    preDraft: function ({ settings }) {
+    preDraft: function ({ settings, store }) {
       for (const i in settings) {
-        if (settings[i].measurements) {
-          if (typeof settings[i].measurements.bust === 'undefined') {
-            settings[i].measurements.bust = settings[i].measurements.chest
-            settings[i].measurements.chest = settings[i].measurements.highBust
-          }
-        }
+        if (
+          settings[i]?.options?.draftForHighBust &&
+          settings?.measurements?.highBust &&
+          typeof settings[i]?.measurements?.bust === 'undefined'
+        ) {
+          store.log.info(
+            'Using `chest` as `bust` measurement and `highBust` as `chest` measurement.'
+          )
+          settings[i].measurements.bust = settings[i].measurements.chest
+          settings[i].measurements.chest = settings[i].measurements.highBust
+        } else store.log.info('Using regular `chest` measurement.')
       }
     },
   },
```

```diff
--- a/designs/brian/src/base.mjs
+++ b/designs/brian/src/base.mjs
@@ -1,4 +1,4 @@
-import { withCondition as bustPlugin } from '@freesewing/plugin-bust'
+import { bustPlugin } from '@freesewing/plugin-bust'
 
 export const base = {
   name: 'brian.base',
```

```diff
--- a/designs/onyx/src/base.mjs
+++ b/designs/onyx/src/base.mjs
@@ -1,4 +1,4 @@
-import { withCondition as bustPlugin } from '@freesewing/plugin-bust'
+import { bustPlugin } from '@freesewing/plugin-bust'
 
 function draftBase({
   utils,
```

```diff
--- a/designs/shelly/src/base.mjs
+++ b/designs/shelly/src/base.mjs
@@ -1,4 +1,4 @@
-import { withCondition as bustPlugin } from '@freesewing/plugin-bust'
+import { bustPlugin } from '@freesewing/plugin-bust'
 
 function draftBase({
   utils,
```

```diff
--- a/designs/tamiko/src/top.mjs
+++ b/designs/tamiko/src/top.mjs
@@ -1,4 +1,4 @@
-import { withCondition as bustPlugin } from '@freesewing/plugin-bust'
+import { bustPlugin } from '@freesewing/plugin-bust'
 
 function tamikoTop({
   sa,
```

**Comment by joostdecock** [comment]
Thanks @BenJamesBen I've implemented pretty much exactly his (but I did not see it before, if not I would have updated the other designs) but I used the `preSetDraft` lifecycle hook so we can check it for each set. See #6079

The end result is that this bug is fixed:
![image](https://github.com/freesewing/freesewing/assets/1708494/6db2c51c-dfec-4ef2-b9a6-0dba61c33015)
