### ISSUE TITLE
[docs]: Add missing org jargon

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6102]
### Suggested content

Previous org jargon terms, with their previous descriptions, that need to be added to the new jargon files:
```json
  "freesewing.d": "<b>FreeSewing</b> is an open source platform for made-to-measure sewing patterns",
  "patternOptions.d": "The <b>pattern options</b> allow you to customize the design of the pattern",
  "draftSettings.d": "The <b>draft settings</b> give you control of how a pattern is generated",
  "patrons.d": "Patrons support Freesewing financially. They are loyal supporters who ensure a sustainable future for freesewing.org, our code, our patterns, and our community.",
  "msf.d": "Médecins Sans Frontières/Doctors Without Borders - See <a href='https://msf.org/'>msf.org</a>"
```

Issue 1:
It is unclear where the files for the new terms should be located. Some possibilities are:
1. `/markdown/org/docs/terms` (top-level in Documentation)
2. `/markdown/org/docs/about/terms` (About FreeSewing)
3. `/markdown/org/docs/about/site/terms` (About the Site)

Issue 2:
It is also unclear what the procedure is for adding translations to the `sites/org/components/jargon.mjs`.
- As I understand it, this file doesn't get translated via Crowdin.
- If I add a new jargon key in English, it seems that I would also have to add the keys in the other languages as well, using the English term temporarily. 
- Eventually the documentation page for the term will get translated, making the translated terms available. 
- It would seem that someone would need to remember to manually add the translations back into the `sites/org/components/jargon.mjs` at a later date.

Issue 3:
I note that instead of creating individual pages for each term, we could instead have just one page containing many terms. I'm not sure whether one method might be preferable over another.
```js
const jargon = {
   en: {
     'freesewing': 'docs/terms/glossary#freesewing',
     'msf':        'docs/terms/glossary#msf',
    },
}

### Additional context

_No response_

**Comment by joostdecock** [comment]
@BenJamesBen A little bit of clarification on why this was closed:

> *Previous org jargon terms, with their previous descriptions, that need to be added to the new jargon files*

Just because something was defined once doesn't mean it needs to be defined always.
For example, having `freesewing` or `msf` as a term is probably overkill

> *It is unclear where the files for the new terms should be located*

Terms our just documentation pages now. There is no reason to think of them as *all terms should go together*.
For example, on FreeSewing.org `docs/about/site/account/id` is a term and so is `docs/sewing/basting`.

> *It is also unclear what the procedure is for adding translations*

The jargon list is not auto-generated. To mark something as a term, just set this in frontmatter:
```
jargon: true
```
See the updated https://freesewing.dev/guides/markdown/jargon for details (once it's deployed)
