### ISSUE TITLE
[bug]: YAML and JSON buttons missing for incomplete measurement sets

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#6329]
### What seems to be the problem? 🤔

For measurement sets with all measurements, a JSON and YAML button appears for exporting the measurement sets. 
For measurement sets with any missing measurements, the buttons are missing.

![image](https://github.com/freesewing/freesewing/assets/4170521/68f72d1c-272a-41a5-8810-4bd00e6c1754)

**Comment by BenJamesBen** [comment]
This issue has to do with public vs. non-public Measurements Sets. It is not related to complete vs. incomplete Measurements Sets.

Only public Measurements Sets have a JSON and YAML button. And, the resulting JSON and YAML URLs only work for public Measurements Sets.

So, for incomplete-but-public Measurements Sets, the JSON and YAML buttons appear. For complete-but-private Measurements Sets ,the JSON and YAML buttons do not appear.

Screenshot:
![Screenshot 2024-03-09 at 4 22 52 PM](https://github.com/freesewing/freesewing/assets/109869956/f3d462d7-bf82-4921-8830-1cfe1ead2cb4)

**Comment by joostdecock** [comment]
As @BenJamesBen points out, the distinction is between public/private sets.

The underlying reason is because these JSON/YAML buttons point directly to the resource's URL on the backend. 
Something like `https://backend3.freesewing.org/sets/1.json`.

That `GET` request will not contain any authentication data, which is why it only works for public data/measurements sets.

Working around that would mean we have to overhaul the way authentication is handled, storing the JSON web token in a cookie rather than local storage, so it would get sent along with that GET request.

I think that's a bit overkill, and overhauling the authentication would probably be a breaking change. So let's do that in v4 :)

For the time being, I've changed is so that these buttons popup a modal window with the relevant data with a 'copy to clipboard' button:

![image](https://github.com/freesewing/freesewing/assets/1708494/be7a3c86-f4cb-4701-ae9e-0061803f62d5)

The fix is in #6371 Closing as that will be merged soon.
