### ISSUE TITLE
[feature]: Dynamically generate use-design.mjs in the lab

### ISSUE THREAD

**Issue by roel-v** [freesewing/freesewing#6397]
### What is it that you would like to see happen? 🤔

I'd like all designs in a lab's 'design' directory to be picked up automatically, meaning, whatever directories are in there, are treated as designs, and are available in the list when you click on 'Design'. So whenever the lab is started, this file gets regenerated, or even nicer, any new directories in 'design' are automatically added.

**Comment by joostdecock** [comment]
@roel-v When you say `a lab's design directory` are you referring to the stand-along development environment?

To be clear:
- `lab`: A stripped-down freesewing.org that has all our designs, but no documentation and so on
- `sde`: The stand-alone development environment that is created by `npx @freesewing/new-design`

**Comment by roel-v** [comment]
Ah yeah sorry I meant sde then, wasn't aware of that difference.

**Comment by joostdecock** [comment]
I have added this [to our roadmap](https://github.com/freesewing/freesewing/discussions/1278) linking back to this issue for context.

I'm going to close this because this will take a while to implement, so the roadmap is a better place to track this so we don't get snowed-in under a long list of issues that will be open for months.

That being said, the fact that it's on the roadmap means we're committed to make this happen.
