### ISSUE TITLE
[bug]: Bookmarked measurement picker fails listing measurements from other users

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6538]
### What seems to be the problem? 🤔

When I bookmark a measurement set from another user, these doesn't appear in the bookmarked measurement set list when creating a pattern. Only your own measurement sets appear there (which is pretty useless as these appear under "your own measurement sets", too).

 Debugging reveals, that the measurement set is known, but then the browser tries to fetch it by requesting something like https://backend3.freesewing.org/sets/[id]/jwt, which fails authentication.

In `sites/backend/src/routes/sets.mjs` it looks like only yaml and json values may be downloaded from public sets from other people. But the jwt route is forbidden (`{"result":"error","error":"insufficientAccessLevel"}`).

I see the following options to fix it:
A) Allow public access for the jwt route
B) Make the measurement picker download the data using the yaml or json route instead

What would be the right approach?

### Design / Plugin / Package 🧐

sites/backend, sites/org

**Comment by joostdecock** [comment]
You can only bookmark another user's set if they are public.

But the backed enforces RBAC without checking whether or not the set is public.

So the fix is to update the `guardedRead` method in the set model to first load the set from the database, check whether it's public or not, and only apply access control if it's not.

**Comment by joostdecock** [comment]
After discussing with @HaasJona on Discord, I'll take this up

**Comment by joostdecock** [comment]
@HaasJona The fix is now running in production. Any chance you could check to make sure it's working as expected?

I can't reproduce (I mean, I can but I'd have to create a new account because my account has elevated privileges, so it would pass the RBAC check in any case), so if it's easy for you, please confirm :)

**Comment by HaasJona** [comment]
It's working fine now!
