### ISSUE TITLE
[docs]: Add missing documentation for Jane's design options

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#6739]
### Where can we see the problem? 🤔

http://localhost:8000/docs/designs/jane

### Suggested content

Please add docs for the options in Jane.

### Additional context

Note that I've already created all the folders and files in #6738 you just have to write the descriptions.

**Comment by bobgeorgethe3rd** [comment]
- [ ] Missing design option documentation
- [ ] Missing designer note documentation
- [ ] Incorrect dates. 1790s not 1970s
- [ ] `options.sleeveLength` would actually be `sleeveLengthBonus` hence why it was originally `sleeveBonus`. Really the sleeve length is set and you simply adding more so it should be bonus rather than just length.
