### ISSUE TITLE
Investigate discrepancies between measurements graph on models page and pattern page

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#674]
See discussion at https://discordapp.com/channels/698854858052075530/757632953097388043/774960503738204171

**Comment by Lobotomik** [comment]
Here is an illustration comparing the graph for all sizes. 

* The graph above shows the measurements for different sizes as they appear when making a Simon shirt. 
* The graph below is the one that is shown in the page where custom measurements are captured for people.
* The points in the black line on both graphs is my own measurements. Let's call it MyLine.

MyLine looks just the same in both graphs. However, the other lines representing the sizes are quite different. 

* In the Simon graph MyLine is mostly in the extremely small sizes (venturing evan far below 3XS in some points).
* In the measurements page graph, MyLine is much more centered, mostly wandering between XL and S.

Let's not go into just why my measurements look so freakish. At least one of the pages is wrong (and possibly both). 

For example:  Hips circumference is between 75 (3XS) and 125 (4XL) in the measurement capture page, but between 70 and 105 in the Simon page. The spread in one case is about 50cm, but only 35 in the other. There would be quite a large scaling difference,  plus offset if there is indeed a linear relation. I guess, though, that there is no relation at all and the values are simply pulled from different places.

![image](https://user-images.githubusercontent.com/24698159/103180216-028bad00-4894-11eb-9971-7ab80fd34a43.png)

**Comment by Lobotomik** [comment]
I have created a person and input the measurements for size M as shown in https://freesewing.org/sizes.

This is the graph in the measurements page:
![image](https://user-images.githubusercontent.com/24698159/103212292-afa10c80-490a-11eb-9bc9-d2af0cbc141d.png)

The black line points are exactly as considered for size M. However, the graph for size M in this page is very different.

I have then made a Simon shirt for the size-M user. The black line for Mr.M and size M in the graph match exactly.
![image](https://user-images.githubusercontent.com/24698159/103212458-19b9b180-490b-11eb-94b7-c8cb9649d633.png)

So the issue is in the measurements page for people. It may be reading stale values from somewhere different than the Simon page.

**Comment by joostdecock** [comment]
Thanks for the sleuthing. I hope to be able to look into this later this week.
