### ISSUE TITLE
Write an introductory arcticle for anyone new to the concept

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#675]
Lara writes:

> Hi there, I'm pretty new here and I'd like to make a suggestion. When I first stumbled upon freesewing I was quite overwhelmed with all the options. Maybe  one could write an introductory arcticle for anyone new to the concept, that takes someone through the first steps of using the patterns, inputing measurments etc. It might make the website more accessible and gives a quick overview of how one would work with the patterns.

Certainly a good idea. What would such an article need to cover? Feel free to comment below with your inputs/suggestions.

**Comment by LaraDE03** [comment]
I have taken a look at the website and come up with some ideas what should be in the article& how it should be structured:

- I would suggest the article is featured right on the landing page (freesewing.org) next to the "x is a patron" building block
  or further down, under the "Further Reading" section. 
![image](https://user-images.githubusercontent.com/74190699/98545370-ad6ceb00-2295-11eb-987d-f24625250cc6.png)
- It could be a small block, with writing along the lines of "New to freesewing? Start with this article!"

- In the article itself it could briefly be explained:
   1. What freesewing is/ who are the people behind it
   2. How the patterns work
   3. How one could join, help etc. the community

Each section could link to a longer or more detailed explanation, for example Point 2 "How the patterns work" links to ->https://freesewing.org/designs/

In the rest of the article I'd write a short tutorial that describes all steps from choosing the pattern to the finished garment, by following a easy sewing pattern for example the "Aaron A-Shirt", so that a visitor has an idea of how the process works.

That's the basic idea, I you would like to add something or find something unnecessary, please let me know!

**Comment by tangerineshark** [comment]
I don't know how to do all of the pieces of this task (like updating the landing page), but I could have a go at some of the content around first steps for a new user (basically (ii) in the comment above). Maybe a walkthrough with screenshots starting at the landing page and getting you to your first drafted pattern, with a nod to the Community page to hit (i) and (iii)? LMK if this sounds helpful!

(Honestly, it also sounds like a solid contender for a YouTube tutorial, but there's a bigger logistical hurdle in that I don't know how to do that yet.)

**Comment by joostdecock** [comment]
Screenshots are dangerous. The website rarely stays the same for more than 6 months because I am never happy with it :wink: 

In general, the homepage (and perhaps the website in general) does a poor job at explaining what FreeSewing is/does.
Ask anyone who knows a thing or two about a thing or two and they will tell you that when people land on your website, they should *get* what it is you're doing. 

I think we fail at that currently. And I'd love to try to improve that. And while articles and YouTube tutorials are great flanking measures to make that happen, we need to get the TLDR right.

I just seem to be pretty bad at it, so I rarely get anywhere. My last notes on this topic include things like:

 - **Come for the sewing patterns, stay for the community** as a slogan (shamelessly ripped from Drupal a number of years back, but they don't use it anymore)
 - A **For makers**, **For designers**, and **For developers** little blurb (rule of three works well)
 - A similar triplet about what makes our patterns special (there's already some of that on the homepage)

Or perhaps we need to try and find somebody who is better at this than I am :wink:

**Comment by tangerineshark** [comment]
Hmmm... (I am also anti-screenshot, because they're only as accessible as their alt text, which is generally not good enough or there wouldn't be a screenshot in the first place, so we'll put a pin in that.)

A lot of what you want people to intuit from the main page does exist in various places (FAQs, documentation, Discord...), and it's more a matter of daylighting it, I think. I don't know how much is on the agenda for upcoming Community Team meetings, but maybe that would be a good place to start the conversation? (Unless you think it would be better to come up with a proposal first, so the feedback in the meeting is less wide-ranging.)

There may be some more mundane documentation for makers that also would help, which would just need to be updated occasionally. If so, I can take that on, once the needs are a little more defined. (Online training/learning is very much in my wheelhouse, and the FreeSewing website is waaaay better than the platform I've been working with.)

(Sorry this is a bit rambling, will consider more over the holidays.)

**Comment by joostdecock** [comment]
I might try to order my thoughts on the matter and make a more substantiated proposal.  
I do agree though that most of the material is available somewhere. So it's really more about making sure (more) intuitively *get it*.

**Comment by tangerineshark** [comment]
No pressure - I was just poking around for something interesting/useful to do over the holiday break, not trying to make more work! 😬

**Comment by joostdecock** [comment]
Here's a quick mockup of what I had in mind. Essentially a click-through for our 3 demographics (makers, designers,developers) that would then reveal some more info below, rather than navigate away from the home page.

![Screenshot_2020-12-23 FreeSewing homepage mockup(1)](https://user-images.githubusercontent.com/1708494/102987557-ce6e6000-4512-11eb-9441-f0e6521c2b7f.png)

I don't much like the top part of the mockup, but I do like them boxes, courtesy of Roy's drawings :slightly_smiling_face: 

I need to add a newsletter signup to the homepage anyway, so I could try to make this happen during the holidays, if you think this works somehow. There is still important work to be done in the text that sits behind those boxes that is supposed to explain things in a concise yet clear way.  
(also the text in the boxes can change, it's pretty much placeholder at this point)

**Comment by joostdecock** [comment]
@LaraDE03 To bring this back to your initial suggestion, the idea would be that if you click on **For makers** you would get what you said was needed: A quick intro with links to more in-depth reading.

By splitting it up per demographic, we can limit ourselves to covering the topics relevant for each group (and avoid a wall of text)

**Comment by woutervdub** [comment]
> I don't much like the top part of the mockup, but I do like them boxes, courtesy of Roy's drawings 🙂

I like the boxes too, and I'm a huge fan of Roy's art. But the first thing I thought when I saw that was: "great gender role confirmation right there."

**Comment by joostdecock** [comment]
> "great gender role confirmation right there."

They are all women :thinking:

**Comment by joostdecock** [comment]
Sorry Penelope :joy: 

![Screenshot_2020-12-23 FreeSewing](https://user-images.githubusercontent.com/1708494/103011314-ff15c000-4539-11eb-9dad-819eef3258c7.png)

**Comment by LaraDE03** [comment]
Ups, sorry I was absent for a bit. I, too, think the idea with the boxes is great, it makes it a lot more intuitive. @tangerineshark I would love to see your idea of the walkthrough, maybe we could make a decent little article combined! (I think it would be a lot better if two or more people are involved in writing it, because the framing from which I approach the task, may not be the same as others and thus the article would be quite one-sided). 
At the moment I am occupied with a new job I just started, so I'll probably wont get around to writing the article until mid-January.
Until then, Happy Holidays everyone! 🎄

**Comment by woutervdub** [comment]
> They are all women 🤔

Well, that shows my gender bias. I just assumed the last one was male.

**Comment by joostdecock** [comment]
It is deliberately ambiguous, so there's no right and wrong. But your remark was valid because I just sort of plucked 3 images without giving it much though, and turns out it wasn't well balanced with two white people, so that was a good input and I've fixed it :)

**Comment by joostdecock** [comment]
Preview deployed on https://next.freesewing.org/

**Comment by joostdecock** [comment]
Here's a screenshot of what's currently deployed at https://next.freesewing.org/ 

![Screenshot_2021-01-07 FreeSewing](https://user-images.githubusercontent.com/1708494/103919265-23fc5c80-5110-11eb-8307-d30e161b2ca4.png)

That **New here?** thing in the top-right links to our new getting started guide: https://next.freesewing.org/docs/guide/  
One remark: It only shows up if you're not logged in (since if you're logged in, you're not new)

I'm certain there is room for improvement in the getting started guide, and I welcome your suggestions.  
Feel free to create a new issue for that (or just [submit a pull request with your improvements on our markdown repo](https://github.com/freesewing/markdown/tree/develop/org/docs/guide)), as I'm closing this one :slightly_smiling_face:
