### ISSUE TITLE
SVG opens with all piece overlapping in Adobe Illustrator and Photoshop 

### ISSUE THREAD

**Issue by nutation** [freesewing/freesewing#692]
SVGs open with all pattern pieces in the upper right of the image on top of each other in Adobe Illustrator and Photoshop. 

PS files open correctly

**Comment by sannek** [comment]
I tried importing an SVG to Illustrator (2021) and had the same issue. The artboard seems to be the correct size to fit all pieces next to each other. It complained about a few things when opening but those don't seem related to the positioning of the pieces.

<img width="502" alt="Screenshot 2020-11-23 at 13 52 26" src="https://user-images.githubusercontent.com/17491062/99965131-baf59b00-2d94-11eb-8cf5-a48f7ed3435e.png">
<img width="452" alt="Screenshot 2020-11-23 at 13 52 54" src="https://user-images.githubusercontent.com/17491062/99965138-bcbf5e80-2d94-11eb-8bc1-e3c87a66498e.png">

**Comment by sannek** [comment]
The issue seems to be that some svg groups have two `translate` on them, and the second one has a space between `translate` and `(` (like here: `<g id="fs-part-cuff"  transform="translate(12, 12) translate (130, 577)">` ) 

Removing that space seems to fix the issue (while still being good in the browser - didn't test anywhere else)
