### ISSUE TITLE
[bug]: Shading on Charlie instructions is confusing

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6959]
### What seems to be the problem? 🤔

Good and bad sides are not using a consistent color in the steps where the front sleeves are attached

See https://discord.com/channels/698854858052075530/1147997959489863780/1262056805056512070

### Design / Plugin / Package 🧐

designs/charlie

**Comment by BenJamesBen** [comment]
From the Discord discussion:

Salieri — 07/14/2024 7:49 AM
> I’m also stumped. I’m trying to line everything up according to the images and with right or wrong sides of fabric correct as shown in the images. But I don’t understand how in one image the pocket and front panel are wrong sides facing (first pic) and then later (after the back and front panels are sewn to the pocket) it looks odd. It looks like in my second picture that after sewing, the panels are ‘unfolded’ but it doesn’t make sense to me how now the pocket lining has right sides facing me and the pant panels are wrong sides facing me. 
![IMG_1005](https://github.com/user-attachments/assets/fba21781-5040-4c85-953f-7c5497a3a2cf)
![IMG_1006](https://github.com/user-attachments/assets/99ae8f1f-ce03-453f-ae91-9f95cd032522)

RockerKitten — 07/14/2024 8:00 AM
> the second pic (with the red arrows) should be all right side facing one direction.
so that when you fold at the pocket to sew the pocket and side seam all the right sides are facing right sides, and the wrong sides will be on the outside. (hopefully I'm making sense) then when turned right side out. the inside of the pockets will be the "right side" as well so when you reach into your pocket, if any of it is see, the pocket bag is also the right side of the fabric.

Salieri — 07/14/2024 8:04 AM
> That makes sense to me. I sewed it that way. I was confused on the pattern shading and assumed the white was the right sides and the shaded side was the wrong sides, but that must not be the case in these pictures. Thanks!

RockerKitten — 07/14/2024 8:05 AM
> yah, I'm not sure why the shading is the way it is either, usually it's correct, but occasionally it's not. 😅

Jonathan Haas — 07/14/2024 8:06 AM
> Don't trust the shading, in step ~7~ 6 it's also wrong. 
I think it's best if you default to good-sides-together and do generally what makes sense.
