### ISSUE TITLE
'#notch' and '#bnotch' are missing from the Draft React component

### ISSUE THREAD

**Issue by ephphatha** [freesewing/freesewing#757]
**What seems to be the problem?**

The shared svg elements for notches are not rendering in patterns or the [notation legend](https://next.freesewing.org/docs/about/patterns/notation/#notches). For example the back piece of Carlton (using a [size 40 template](https://en.freesewing.org/create/carlton/for/size-40-a/) as an example) should have a bnotch on the top right corner and the top vertex of the dashed triangle visible on the left of the pattern.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Looking at the DOM the shadow-root context is empty whereas for something like a button or the logo it correctly shows the path defined for that ID. It looks like these elements are defined in [plugin-theme/src/defs/notch.js](https://github.com/freesewing/freesewing/blob/develop/packages/plugin-theme/src/defs/notch.js). I suspect this package isn't being bundled or loaded. The plugin-theme package might need to be imported in each pattern that uses notches (similar to how plugin-buttons is loaded) or added to plugin-bundle?

**Comment by joostdecock** [comment]
Well spotted :)

We have two ways to render patterns:

 - Render as an SVG string
 - Render as a React component

![Screenshot_2020-12-27 Pattern building blocks](https://user-images.githubusercontent.com/1708494/103169532-ca0cb480-483c-11eb-8c8d-b7ca2949fc04.png)

On the website, we use our React component because it provides superior interactivity. It is in this React component that the notches are missing.

The notch is present in the plugin-bundle, which explains that the notch will be there when you export SVG or PDF: https://static.freesewing.org/tmp/bkwxmdigud/pattern-full.pdf

I'm updating the title accordingly.

**Comment by joostdecock** [comment]
So TIL that I'm for of it :slightly_smiling_face: 

The `notch` and `bnotch` snippets are not part of plugin-bundle because they are not provided by any of the build-time plugins.
Instead, they are provided by the theme plugin. This is why it *works* when rendering to SVG on freesewing.org because we include the theme there at run time. But we do not use it to style React components, which has its own CSS.

So, without the theme included, there's no notches. That's a bit of a pickle because the theme plugin should only provide styling, and no functionality. So I'm planning to move the notches that are provided in the theme plugin to another plugin. Probably include it into buttons which already has buttons and buttonholes and snaps. While its name is becoming perhaps increasingly misleading, at least it's a build-time plugin which would be the better way to address this.

I have made an intermediate fix now that adds them the `Example` component manually, as this fixes things on freesewing.dev.
I will need to look into the effect on freesewing.org before implementing this, so I'm keeping this open.

**Comment by joostdecock** [comment]
Ended up putting this in [@freesewing/plugin-notches](https://www.npmjs.com/package/@freesewing/plugin-notches)

**Comment by joostdecock** [comment]
This took some work, but is now properly fixed. Will be deployed with the v2.11 release.
