### ISSUE TITLE
Description of hem radius not displayed

### ISSUE THREAD

**Issue by ttimearl** [freesewing/freesewing#821]
**Description of hem radius missing**

While drafting Wahid, I displayed Design options/Style. When hem radius is selected drop down description displays *options.wahid.hemRadius.description* and not an actual description.

This my first issue (anywhere, not just on FS). Any tips are welcome (e.g. should I have added assignees or labels?)

**Comment by joostdecock** [comment]
Congratulations on your first issue @ttimearl :+1: 

You did everything right. Assigning labels and so on are things that you can only do when you have the proper access rights.
I will add you as a contributor to the FreeSewing organisation, and once you accept the invite (you'll receive an email), you'll be able to assign labels and so on.

But when you create an issue in a project you are not involved in, it's up to the people who run the project to assign labels. Something that's typically referred to as **triage** and is a good way to help out :wink: 

As for the problem at hand, when you see a `something.something` string like that, it's because the translation is missing.
In this case, the translation is there, but there's a typo in the word `description`: https://github.com/freesewing/freesewing/blob/develop/packages/i18n/src/locales/en/options/wahid.yml#L35

I invite you to fix that typo by clicking the link above and clicking the pencil icon to edit the file.
Then fix the typo, and you can submit your changes.

At which point you will have made your first code contribution to an open source project :nerd_face:

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/58d4407f2575bfd7eefceabd1cb7abadfaef030f
