### ISSUE TITLE
Broken links on "for contributors" page

### ISSUE THREAD

**Issue by geeksam** [freesewing/freesewing#833]
[I tried grepping for the links in the .org and .dev repos, but didn't spot anything.  I'd be happy to submit PRs for at least two of the below if you'll point me to the appropriate repo.]

On the [freesewing.dev contributors page](https://freesewing.dev/contributors/):

* "our community standards" links to `https://freesewing.org/docs/about/community-standards/`.  I couldn't figure out where this content actually is.  :)
* "revenue pledge" links to `https://freesewing.org/docs/about/pledge/`.  The link in the footer points to `https://next.freesewing.org/docs/various/pledge/`; this should probably match.
* "Ways to contribute" links to `https://freesewing.dev/contributor/ways-to-contribute`.  This appears to just be a simple typo, since I found what looks like the correct page by adding an 's' to the word 'contributor'.

**Comment by joostdecock** [comment]
Thank you for reporting this, much appreciated!

Our markdown/mdx content is in [our markdown repository](https://github.com/freesewing/markdown/).
The file you are looking for is: https://github.com/freesewing/markdown/blob/develop/dev/contributors/en.md

I'll leave it to you to fix it, since you indicated a willingness to do so, and I love contributions big and small :)
