### ISSUE TITLE
Create Sandy showcase from Discord post

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#845]
- Content:  Discord
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author. The author, TheViolentChef on Discord, granted permission on Discord
 - Username: Please ask the author for their FreeSewing username

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site]( https://freesewing.dev/editors/howtos/showcase/).

**Comment by nataliabarnhart** [comment]
I'll ask for the author's FreeSewing username and create the showcase. Just wanted to try out opening an issue 😁

**Comment by joostdecock** [comment]
Well you nailed it :joy: 

FYI: Since a recent update, we no longer list the freesewing username on the showcase.  
Trying to get people's username was adding a lot of friction to the process, and without much added value, so we dropped it.

That should make it simpler to add showcase pasts. You can still link to give credit, either to instagram, twitter, discord, or wherever the picture is from.

I might have forgotten to update the docs though :thinking:

**Comment by joostdecock** [comment]
Oh forgot: This issue will only appear on the project board if you assign it to the `freesewing` project (which I'll do next)

**Comment by nataliabarnhart** [comment]
Thanks @joostdecock !!
